[std] Fix dangling \grammarterms.
cplusplus/draft pull request #4130
Opened 2020-08-28 17:07 UTC by Eelis

2020-08-28 17:18 UTC, jensmaurer commented on source/expressions.tex
> +of a \grammarterm{init-statement}, an \grammarterm{await-expression}
This needs to become "of an init-statement".

2020-08-28 17:18 UTC, jensmaurer requested changes
This needs an English fix.

2020-08-28 18:06 UTC, jensmaurer approved these changes

2020-08-28 18:06 UTC, jensmaurer commented
@tkoeppe, could you have a look, please?

2020-09-08 23:59 UTC, Eelis commented
Amended to add a fix for
https://github.com/cplusplus/draft/blob/06b83178c131cde51526a1fd68925b73f2f699e5/source/compatibility.tex#L41
(should be `module-import-declaration`).

2020-09-09 09:07 UTC, jensmaurer approved these changes

2020-09-18 04:36 UTC, merged