[depr.c.header.others] Add 'std::nullptr_t' to the list of names NOT declared by stddef.h.
cplusplus/draft pull request #4145
Opened 2020-09-06 20:00 UTC by tkoeppe

Fixes #4144.

2020-09-06 20:42 UTC, jwakely requested changes
NACK. I think this is a normative change, because currently `<stddef.h>` is required to declare `::nullptr_t`. That's how libstdc++ and libc++ interpret it.

C.6.3 [diffs.mods.to.declarations] is informative (not normative), and my interpretation is that it's saying "The C++ version of this header adds `nullptr_t`, which isn't in the C version of this header". It's not saying that `<cstddef>` declares it and C++'s `<stddef.h>` doesn't.

2020-09-06 20:50 UTC, tkoeppe commented
You're right. Should we create an issue for this then? (I still think this is a desirable change, but it is indeed normative.)

I will replace the wording changes here with those for [diffs.mods.to.declarations].

2020-09-06 21:01 UTC, tkoeppe commented
@jwakely: PTAL.

2020-09-08 12:27 UTC, jwakely approved these changes

2020-09-08 14:41 UTC, merged