[stmt.ranged] Align font for begin-expr and end-expr.
cplusplus/draft pull request #4289
Opened 2020-10-06 17:23 UTC by jensmaurer

Those are placeholders for expressions.

Fixes #4285

2020-10-18 03:26 UTC, zygoloid commented
@tkoeppe I'd like your opinion on the cacophony of fonts in use here. We have upright text, slanted grammar terms, italicized placeholders, teletype code, and slanted teletype exposition-only IDs, in a short space. And the teletype font have rather different font weight when used in the codeblock and when used in running text (eg, in bullets (1.2) and (1.3.2)).

The use of `grammarterm` for the `begin-expr` and `end-expr` is certainly wrong, but I wonder if there's more here that we could improve.

2020-10-18 16:28 UTC, tkoeppe commented
I'll take a look. I had similar thoughts when the issue was first raised.

2020-10-18 21:33 UTC, tkoeppe commented
(Tangent: I think the font weight of the slanted teletype is always quite big, even in the codeblock. There's just less roman font around for comparison. We can look into that separately.)

2020-10-18 21:34 UTC, tkoeppe commented
I wouldn't be opposed to more "slanted teletype" for these expression placeholders. Nothing says we can use that style only for placeholder variables, and indeed we areadly happily use it for placeholder types and concepts I believe.

2020-10-19 14:49 UTC, tkoeppe requested changes
In my opinion we could use `\exposid` everywhere for the two expr-placeholders and it wouldn't look all that confusing. We already use italic-teletype for a variety of placeholders (concepts, namespaces, types), so I don't have a problem with also using it for expressions.

2020-10-28 22:06 UTC, tkoeppe commented
@jensmaurer: Looks like something went wrong with the push, could you check again?

2020-10-28 22:13 UTC, jensmaurer commented
@tkoeppe , should be better now.

2020-10-28 23:12 UTC, tkoeppe approved these changes

2020-10-29 21:57 UTC, merged