Fix up the wording of one note, and add a second note, on implicit move.
cplusplus/draft pull request #4408
Opened 2020-12-05 17:19 UTC by Quuxplusone

These notes probably should have been changed when P1825 was adopted.

I'm not sure if this is editorial.

Also, I disagree with the use of the word "can" in the existing note; it seems to me that this is *not* a choice the user gets to make, and so this was an incorrect search-and-replace in e5455e3bb — but maybe this is just ISO style now, I dunno.

2020-12-06 19:51 UTC, jensmaurer commented
This is mostly fixed with #3998, I believe.

2021-02-07 22:17 UTC, jensmaurer requested changes
Please make sure the commit description is properly formatted.
It should start with the [section.label] and then describe the change.

For this particular change, maybe it's less relevant that we changed two notes,
but more relevant that we now highlight implicitly movable entities.
Suggestion: "Fix and add notes about implicit moving in co_/return statements"

2022-08-22 21:10 UTC, tkoeppe commented
Please reopen (and rebase) if you'd like to continue working on this.

2022-08-22 21:10 UTC, closed without merging

2022-08-23 05:23 UTC, Quuxplusone commented
I'm not actually sure how to reopen; but I have rebased now (and updated the commit summary line).

2022-08-23 08:32 UTC, tkoeppe commented
Oh, I see, the reopen button isn't working for me either. Odd. Did you "recreate" the branch? In that case maybe you could start a new pull request off that branch?

2022-08-23 14:31 UTC, Quuxplusone commented
Okay, opened #5783!