[iterator.concept.winc] Remove "in" in "defined in below"
cplusplus/draft pull request #4470
Opened 2021-01-24 06:06 UTC by johelegp

2021-01-24 06:08 UTC, johelegp commented on source/iterators.tex
>  if it is in a set of implementation-defined class types
```suggestion
if it is in a set of \impldef{integer-class types} class types
```
How does that look?

2021-01-24 08:51 UTC, jensmaurer requested changes

2021-01-24 08:51 UTC, jensmaurer commented on source/iterators.tex
>  if it is in a set of implementation-defined class types
make it singular inside the \impldef

2021-01-24 17:03 UTC, johelegp commented on source/iterators.tex
>  if it is in a set of implementation-defined class types
Fixed.

2021-01-24 17:06 UTC, jensmaurer approved these changes

2021-01-29 23:09 UTC, CaseyCarter approved these changes

2021-01-30 19:53 UTC, merged