P2162R2 Inheriting from std::variant
cplusplus/draft pull request #4515
Opened 2021-02-23 21:50 UTC by jensmaurer

Also fixes LWG3052.

 - Introduced new type meta-variable FV_i to handle overfull lines.

Fixes #4509
Fixes cplusplus/papers#873

2021-02-23 23:18 UTC, johelegp requested changes

2021-02-23 23:18 UTC, johelegp commented on source/utilities.tex
> +@\placeholder{INVOKE}@<R>(std::forward<Visitor>(vis), get<@$m$@>(std::forward<V>(vars))...) // see \ref{func.require}
```suggestion
@\placeholder{INVOKE}@<R>(std::forward<Visitor>(vis), get<@$m$@>(std::forward<V>(vars))...)  // see \ref{func.require}
```

2021-02-23 23:18 UTC, johelegp commented on source/utilities.tex
> +@\placeholder{INVOKE}@(std::forward<Visitor>(vis), get<@$m$@>(std::forward<V>(vars))...) // see \ref{func.require}
```suggestion
@\placeholder{INVOKE}@(std::forward<Visitor>(vis), get<@$m$@>(std::forward<V>(vars))...)  // see \ref{func.require}
```

2021-02-26 00:14 UTC, burblebee approved these changes

2021-03-07 14:40 UTC, tkoeppe commented on source/utilities.tex
> +
I would lose these newlines around the codeblock. (But I can do that during merging.)

2021-03-07 14:41 UTC, tkoeppe commented on source/utilities.tex
> +
I think we don't want a rogue paragraph break here, do we?

2021-03-07 14:45 UTC, tkoeppe requested changes

2021-03-07 14:45 UTC, tkoeppe commented on source/utilities.tex
> +
I think we lost a paragraph, "Let V denote the pack of types V_i"?

2021-03-09 00:47 UTC, tkoeppe commented on source/utilities.tex
> +
Added.

2021-03-09 00:48 UTC, tkoeppe commented on source/utilities.tex
> +for all $0 \leq i < n$.
It's the pack element. We've used this in a bunch of places. e g. for `tuple`.

2021-03-09 00:51 UTC, tkoeppe approved these changes

2021-03-09 00:52 UTC, merged