[tuple.elem] Replace "member variables" with "data members"
cplusplus/draft pull request #4602
Opened 2021-05-17 11:41 UTC by morinmorin

While I use both terms — data members and member variables — I don't think "member variable" is a defined term in the Standard.

2021-05-17 11:50 UTC, jwakely approved these changes
To be really correct it should be "non-static data members", but it's only a note.

2021-05-17 17:23 UTC, jensmaurer requested changes

2021-05-17 17:23 UTC, jensmaurer commented on source/utilities.tex
> +for data members of reference type.
-> "non-static data members"

2021-05-17 23:31 UTC, morinmorin commented on source/utilities.tex
> +for data members of reference type.
Done!

2021-05-18 19:25 UTC, jensmaurer approved these changes

2021-05-18 19:26 UTC, merged