P1518R2 Stop overconstraining allocators in container deduction guides
cplusplus/draft pull request #4672
Opened 2021-06-09 12:17 UTC by jensmaurer

Fixes #4645
Fixes cplusplus/papers#381

2021-06-09 14:38 UTC, JohelEGP requested changes
Between `vector<bool>` and `multimap`, you missed the `map` changes.

2021-06-11 10:31 UTC, jensmaurer commented
@JohelEGP , thanks, fixed.

2021-06-11 10:52 UTC, jwakely approved these changes

2021-06-16 15:17 UTC, tkoeppe commented on source/containers.tex
> -\item It has an \tcode{Allocator} template parameter and a type that does not qualify as an allocator is deduced for that parameter.
This deletion is at odds with the paper, and the paper is at odds with the status quo. @Quuxplusone, could you perhaps check if the paper is misrepresenting the status quo and was missing this item? (And the item is meant to be retained?)

2021-06-16 15:31 UTC, tkoeppe commented on source/containers.tex
> -\item It has an \tcode{Allocator} template parameter and a type that does not qualify as an allocator is deduced for that parameter.
Never mind, I misread the diff. All good!

2021-06-16 15:32 UTC, merged