P1989R2 Range constructor for std::string_view 2: Constrain Harder
cplusplus/draft pull request #4676
Opened 2021-06-09 16:16 UTC by jensmaurer

Fixes #4649
Fixes cplusplus/papers#714

2021-06-09 16:54 UTC, jensmaurer commented
See http://lists.isocpp.org/lib/2021/06/19670.php for a glitch in the incoming paper.

@tkoeppe , should this be fixed editorially?

2021-06-09 17:08 UTC, JohelEGP requested changes

2021-06-09 17:08 UTC, JohelEGP commented on source/strings.tex
>    // \ref{string.view.deduct}, deduction guide
```suggestion
  // \ref{string.view.deduct}, deduction guides
```

2021-06-09 17:08 UTC, JohelEGP commented on source/strings.tex
> +
```suggestion
```

2021-06-09 17:08 UTC, JohelEGP commented on source/strings.tex
> +\tcode{ranges::contiguous_range} and \tcode{ranges::sized_range},
```suggestion
\tcode{ranges::\libconcept{contiguous_range}} and \tcode{ranges::\libconcept{sized_range}},
```

2021-06-09 17:08 UTC, JohelEGP commented on source/strings.tex
> +\tcode{R} satisfies \tcode{ranges::contiguous_range}.
```suggestion
\tcode{R} satisfies \tcode{ranges::\libconcept{contiguous_range}}.
```

2021-06-11 11:00 UTC, jensmaurer commented
@JohelEGP , thanks, fixed.

2021-06-16 23:04 UTC, tkoeppe commented
@jensmaurer: yes, I'll assume that's fine and will add a fix. I've asked for LWG approval (@jwakely?), but will proceed assuming we'll get that.

2021-06-16 23:06 UTC, merged