P2216R3 std::format improvements
cplusplus/draft pull request #4680
Opened 2021-06-09 21:11 UTC by jensmaurer

- Avoid redundantly presenting the definition of basic-format-string
   in the header synopsis.
 - Do not italicize basic-format-string's private exposition-only member,
   consistent with similar situations.

Fixes #4653
Fixes cplusplus/papers#919

2021-06-09 21:52 UTC, JohelEGP requested changes

2021-06-09 21:52 UTC, JohelEGP commented on source/utilities.tex
> +    struct @\exposid{basic-format-string}@;
```suggestion
    struct @\exposid{basic-format-string}@;  // \expos
```

2021-06-09 21:52 UTC, JohelEGP commented on source/utilities.tex
> +    using @\exposid{wformat-string}@ =                            // exposition only
```suggestion
    using @\exposid{format-string}@ =                             // \expos
      @\exposid{basic-format-string}@<char, type_identity_t<Args>...>;
  template<class... Args>
    using @\exposid{wformat-string}@ =                            // \expos
```

2021-06-09 21:52 UTC, JohelEGP commented on source/utilities.tex
> +  basic_string_view<charT> str;         // exposition only
```suggestion
struct @\exposid{basic-format-string}@ {            // \expos
private:
  basic_string_view<charT> str;         // \expos
```

2021-06-09 21:52 UTC, JohelEGP commented on source/utilities.tex
> +\tcode{const T\&} models \tcode{convertible_to<basic_string_view<charT>>}.
```suggestion
\tcode{const T\&} models \tcode{\libconcept{convertible_to}<basic_string_view<charT>>}.
```

2021-06-11 11:15 UTC, jensmaurer commented
@JohelEGP , thanks, fixed.

2021-06-16 23:48 UTC, tkoeppe commented
@jensmaurer: your commit message indicates that you didn't want to italicize the exposition-only `str` member, but it's still italicised in the current version. Did you intend to change that?

If so, I'm going to open a new issue to do this later. We should also rename `str` to `str_` at that point.

2021-06-17 00:09 UTC, merged

2021-06-17 00:58 UTC, JohelEGP commented
> @jensmaurer: your commit message indicates that you didn't want to italicize the exposition-only `str` member, but it's still italicised in the current version. Did you intend to change that?

I noted that the comment was right before a rebase.

2021-06-17 19:38 UTC, cpplearner commented on source/utilities.tex
> +    Out vformat_to(Out out, string_view fmt, format_args, args);
Extra comma in `format_args, args`

2021-06-17 19:39 UTC, cpplearner commented on source/utilities.tex
> +    Out vformat_to(Out out, wstring_view fmt, wformat_args, args);
Extra comma in `wformat_args, args`

2021-06-17 20:32 UTC, jensmaurer commented on source/utilities.tex
> +    Out vformat_to(Out out, string_view fmt, format_args, args);
fixed in linked pull request

2021-06-17 20:32 UTC, jensmaurer commented on source/utilities.tex
> +    Out vformat_to(Out out, wstring_view fmt, wformat_args, args);
fixed in linked pull request