P0448R4 A strstream replacement using span<charT> as buffer
cplusplus/draft pull request #4687
Opened 2021-06-11 06:06 UTC by jensmaurer

Fixes  #4643
Fixes cplusplus/papers#103

2021-06-11 16:10 UTC, JohelEGP requested changes

2021-06-11 19:11 UTC, jensmaurer commented on source/iostreams.tex
> +\rSec3[ispanstream.assign]{Assignment and swap}
`basic_istringstream` has exactly the same problems.

I'd suggest to be locally consistent and consider a later fix-up, possibly with checking by LWG.

2021-06-11 19:18 UTC, jensmaurer commented on source/iostreams.tex
> +    using traits_type = traits;
Alignment is fixed.

2021-06-16 14:47 UTC, tkoeppe commented on source/iostreams.tex
> +\rSec3[ispanstream.assign]{Assignment and swap}
I filed #4700 for this.

2021-06-16 14:47 UTC, merged