[basic.fundamental] Redirect some index entries.
cplusplus/draft pull request #4689
Opened 2021-06-11 16:23 UTC by Eelis

Only the index is affected.

2021-06-11 20:50 UTC, jensmaurer requested changes
Mostly harmless.

2021-06-11 20:50 UTC, jensmaurer commented on source/basic.tex
> +there exists a corresponding \defnx{extended unsigned integer type}{type!extended unsigned integer}.
Make this `\defnadj{extended unsigned integer}{type}` and you get the "see type, extended unsigned integer" entry for free (the other line can go).

2021-06-12 04:54 UTC, Eelis commented
Amended to use \defnadj

2021-06-12 06:26 UTC, jensmaurer approved these changes
Thanks, much shorter = better now.

2021-06-17 17:54 UTC, merged