P2385R0 C++ Standard Library Issues to be moved in Virtual Plenary, June 2021
cplusplus/draft pull request #4695
Opened 2021-06-12 12:28 UTC by jensmaurer

Fixes #4640

2021-06-12 15:40 UTC, JohelEGP commented on source/containers.tex
> +
```suggestion
```

2021-06-12 15:43 UTC, JohelEGP commented on source/containers.tex
> +Let \tcode{binary_pred} be \tcode{equal_to<>\{\}} for the first overload.
```suggestion
Let \tcode{binary_pred} be \tcode{equal_to\{\}} for the first overload.
```

2021-06-12 15:47 UTC, JohelEGP commented on source/containers.tex
> +Let \tcode{binary_pred} be \tcode{equal_to<>\{\}} for the first overload.
```suggestion
Let \tcode{binary_pred} be \tcode{equal_to\{\}} for the first overload.
```

2021-06-12 21:44 UTC, JohelEGP requested changes

2021-06-12 21:44 UTC, JohelEGP commented on source/iostreams.tex
> +explicit basic_ofstream(const T& s, ios_base::openmode mode = ios_base::out);
```suggestion
template<class T>
  explicit basic_ofstream(const T& s, ios_base::openmode mode = ios_base::out);
```

2021-06-12 21:44 UTC, JohelEGP commented on source/containers.tex
> +initializes \tcode{comp} with compare;
```suggestion
initializes \tcode{comp} with \tcode{compare};
```

2021-06-12 21:44 UTC, JohelEGP commented on source/ranges.tex
> +      requires indirectly_swappable<@\exposid{InnerIter}@>;
```suggestion
      requires \libconcept{indirectly_swappable}<@\exposid{InnerIter}@>;
```

2021-06-12 22:50 UTC, JohelEGP requested changes

2021-06-13 07:54 UTC, jensmaurer commented on source/containers.tex
> +Let \tcode{binary_pred} be \tcode{equal_to<>\{\}} for the first overload.
The incoming text has the `<>` here.

2021-06-13 07:54 UTC, jensmaurer commented on source/containers.tex
> +Let \tcode{binary_pred} be \tcode{equal_to<>\{\}} for the first overload.
The incoming text has the `<>` here.

2021-06-13 07:55 UTC, jensmaurer commented on source/containers.tex
> +
fixed

2021-06-13 07:55 UTC, jensmaurer commented on source/utilities.tex
>  \pnum
fixed

2021-06-13 15:51 UTC, JohelEGP requested changes

2021-06-13 15:51 UTC, JohelEGP commented on source/ranges.tex
> +constexpr iota_view(iterator first, @\seebelow@ last);
```suggestion
constexpr iota_view(@\exposid{iterator}@ first, @\seebelow@ last);
```

2021-06-13 15:51 UTC, JohelEGP commented on source/ranges.tex
> +If \tcode{same_as<W, Bound>} is \tcode{true},
```suggestion
If \tcode{\libconcept{same_as}<W, Bound>} is \tcode{true},
```

2021-06-13 15:51 UTC, JohelEGP commented on source/ranges.tex
> +If \tcode{same_as<W, Bound>} is \tcode{true}, \exposid{iterator}.
```suggestion
If \tcode{\libconcept{same_as}<W, Bound>} is \tcode{true}, \exposid{iterator}.
```

2021-06-13 15:51 UTC, JohelEGP commented on source/utilities.tex
> +  requires @\libconcept{is_constructible_v}@<T, decltype(get<I>(declval<Tuple>()))...>
```suggestion
  requires is_constructible_v<T, decltype(get<I>(declval<Tuple>()))...>
```

2021-06-13 15:51 UTC, JohelEGP commented on source/containers.tex
> +  priority_queue(InputIterator first, InputIterator last, const Compare&, Container&& y);
```suggestion
  priority_queue(InputIterator first, InputIterator last, const Compare& x, Container&& y);
```

2021-06-13 22:10 UTC, JohelEGP requested changes

2021-06-14 09:51 UTC, jensmaurer commented on source/utilities.tex
> +  class @\exposid{format-arg-store}@ {                                      // \expos
Yes; postponed to https://github.com/cplusplus/draft/issues/4698

2021-06-14 09:53 UTC, jensmaurer commented
@JohelEGP , thanks. Applied + force-pushed.

2021-06-16 13:57 UTC, tkoeppe commented
Thank you both, stellar work!

2021-06-16 13:58 UTC, merged