P0847R7 Deducing this
cplusplus/draft pull request #5002
Opened 2021-10-05 18:25 UTC by jensmaurer

Fixes  #4964
Fixes cplusplus/papers#115

2021-10-05 19:02 UTC, JohelEGP requested changes

2021-10-14 18:04 UTC, jensmaurer commented on source/declarations.tex
> +  std::move(c).g(42);           // OK, calls \tcode{C::g<C>}
No, we do "OK,"

https://github.com/cplusplus/draft/pull/971#issuecomment-260205806

2021-10-15 13:25 UTC, JohelEGP commented on source/declarations.tex
> +  std::move(c).g(42);           // OK, calls \tcode{C::g<C>}
Thank you. I was doubting myself on that. It'd be nice to add "error:" to the guidelines wiki. The lack of "OK:" would have made it clearer that it's not as global as "error:".

2021-10-15 16:57 UTC, tkoeppe approved these changes

2021-10-15 16:57 UTC, tkoeppe commented on source/declarations.tex
> +$\tcode{p}_{i+1}$ denotes the $i^\textrm{th}$ non-object function parameter
Ah, you already got it -- nice!

2021-10-15 17:18 UTC, merged