P1272R4 Byteswapping for fun&&nuf
cplusplus/draft pull request #5018
Opened 2021-10-09 08:18 UTC by jensmaurer

Fixes #4982 
Fixes cplusplus/papers#270

2021-10-10 00:05 UTC, CaseyCarter requested changes

2021-10-10 00:05 UTC, CaseyCarter commented on source/numerics.tex
> +  constexpr T byteswap (T value) noexcept;
Ditto "we don't format declarations like this":
```suggestion
  constexpr T byteswap(T value) noexcept;
```

2021-10-10 00:05 UTC, CaseyCarter commented on source/numerics.tex
> +A object \tcode{v} of type \tcode{T}
```suggestion
An object \tcode{v} of type \tcode{T}
```

2021-10-14 21:00 UTC, CaseyCarter approved these changes

2021-10-17 21:01 UTC, burblebee approved these changes

2021-10-19 20:40 UTC, jensmaurer commented on source/numerics.tex
> +of unsigned ordinary character type or \tcode{std::byte type}.
fixed

2021-10-19 23:17 UTC, merged