P2393R1 Cleaning up integer-class types
cplusplus/draft pull request #5026
Opened 2021-10-13 15:10 UTC by jensmaurer

Fixes #4989
Fixes cplusplus/papers#1065

2021-10-14 01:40 UTC, timsong-cpp commented on source/iterators.tex
> +$0$ to $2^{N-1}$ (inclusive) for some integer $N$,
```suggestion
$0$ to $2^{N}-1$ (inclusive) for some integer $N$,
```

2021-10-14 01:42 UTC, timsong-cpp commented on source/iterators.tex
> +For every integral type \tcode{J}, let B(J)c be the same type as \tcode{J}.
```suggestion
For every integral type \tcode{J}, let \tcode{B(J)} be the same type as \tcode{J}.
```

2021-10-14 01:46 UTC, timsong-cpp commented on source/iterators.tex
> +\libconcept{three_way_comparable}<strong_ordering>\iref{cmp.concept}.
```suggestion
\tcode{\libconcept{three_way_comparable}<strong_ordering>}\iref{cmp.concept}.
```

2021-10-14 01:49 UTC, timsong-cpp commented on source/ranges.tex
> +\tcode{subrange(r, static_cast<decltype(\exposid{size_}-)>(ranges::size(r)))}.
```suggestion
\tcode{subrange(r, static_cast<decltype(\exposid{size_})>(ranges::size(r)))}.
```

2021-10-19 08:34 UTC, burblebee requested changes

2021-10-20 01:48 UTC, burblebee approved these changes

2021-10-20 12:44 UTC, tkoeppe commented on source/ranges.tex
> +          auto sz = range_difference_t<V>(size());
Should this say `const V` instead of `V` here? Also two edits below.

2021-10-20 14:29 UTC, jensmaurer commented on source/iterators.tex
> +let \tcode{B(I)} be a unique hypothetical extended integer type
fixed

Author: Jens Maurer <Jens.Maurer@gmx.net>
Date:   Wed Oct 20 16:28:30 2021 +0200

    fixup: use math formatting for B(I)

2021-10-20 14:30 UTC, tkoeppe commented on source/iterators.tex
> +let \tcode{B(I)} be a unique hypothetical extended integer type
Oh, thank you! I thougth we could leave it for a later cleanup, very nice.

2021-10-20 21:02 UTC, merged