[basic.start.main] remove redundant phrase
cplusplus/draft pull request #5083
Opened 2021-10-30 06:54 UTC by timsong-cpp

If "to end the program" is merely describing what `std::exit` does, it's redundant; if it is read as expressing purpose or intent, it's incorrect - whether a program has UB cannot depend on the programmer's intent.

2021-10-31 02:33 UTC, languagelawyer requested changes

2021-10-31 02:33 UTC, languagelawyer commented on source/basic.tex
> +\tcode{std::exit} is called during the destruction of
```suggestion
\tcode{std::exit} is invoked during the destruction of
```
https://github.com/cplusplus/draft/issues/3079#issuecomment-544636262

2021-11-23 17:37 UTC, jensmaurer commented
@timsong-cpp , generally agreed. Could you please apply the "called" -> "invoked" drive-by fix? ("Called" is ambiguous and could mean "named" or "termed": "I call my son Richard", with no connection to function calls.)

2021-11-23 17:49 UTC, jensmaurer approved these changes
Looks good. @tkoeppe , please squash when merging.

2021-11-23 17:51 UTC, merged