[except.throw,except.handle] Move lvalue specification for copies
cplusplus/draft pull request #5092
Opened 2021-11-06 08:41 UTC by jensmaurer

Fixes #5091

2021-11-06 08:41 UTC, jensmaurer commented
@languagelawyer , this should address your concerns.

2021-11-06 10:07 UTC, languagelawyer commented
Still doesn't say anything about the lvalue type.

2021-11-06 11:05 UTC, jensmaurer commented
Do you want "an lvalue of the type of the exception object, designating the exception object"?

2021-11-06 22:21 UTC, languagelawyer requested changes

2021-11-06 22:21 UTC, languagelawyer commented on source/exceptions.tex
> +from an lvalue designating the corresponding base class subobject
```suggestion
from an lvalue of type \tcode{T} designating the corresponding base class subobject
```

2021-11-06 22:21 UTC, languagelawyer commented on source/exceptions.tex
> +from an lvalue designating the exception object.
```suggestion
from an lvalue of type \tcode{E} designating the exception object.
```

2021-11-07 20:34 UTC, jensmaurer commented
Sounds good.

2022-01-14 14:12 UTC, merged