[locale.time.get] Replace 'ISO/IEC 9945' with 'POSIX'
cplusplus/draft pull request #5100
Opened 2021-11-09 12:10 UTC by jensmaurer

We introduce POSIX as an alias for ISO/IEC 9945, and we use 'POSIX'
everywhere else.

2021-11-09 12:12 UTC, tkoeppe commented
@jwakely: could you please take a look?

2021-11-09 13:45 UTC, jwakely approved these changes

2021-11-09 13:53 UTC, jwakely commented
I missed this in [P2227](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2227r0.html) but there are no changes to the `strptime` conversion specifications between [POSIX 2001](https://pubs.opengroup.org/onlinepubs/009696799/functions/strptime.html) and [POSIX 2008](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strptime.html) except for clarifications of the intended meaning.

I'm not fond of the term "conversion directive" here though, POSIX says "directives" contain "conversion specifications". There are no conversion directives.

2021-11-09 13:55 UTC, jwakely requested changes

2021-11-09 16:55 UTC, jensmaurer commented on source/locales.tex
>  corresponding to a conversion directive appropriate for
Added this fix in a separate commit. Also found additional mentions nearby; fixed them, too.

2021-11-12 13:51 UTC, jensmaurer commented
@jwakely , please have another look.

2021-11-12 14:54 UTC, jwakely approved these changes

2021-11-12 15:08 UTC, jensmaurer commented
@tkoeppe , this looks ready.

2021-11-23 16:59 UTC, merged