P2441R2 views::join_with
cplusplus/draft pull request #5248
Opened 2022-02-02 20:08 UTC by jensmaurer

2022-02-02 22:25 UTC, JohelEGP requested changes

2022-02-02 22:25 UTC, JohelEGP commented on source/ranges.tex
> +iterator tmp = *this;
```suggestion
@\exposid{iterator}@ tmp = *this;
```

2022-02-02 22:25 UTC, JohelEGP commented on source/ranges.tex
> +constexpr explicit sentinel(Parent& parent);
```suggestion
constexpr explicit @\exposid{sentinel}@(@\exposid{Parent}@& parent);
```

2022-02-04 22:52 UTC, jensmaurer commented on source/ranges.tex
> +    template<bool Const> struct @\exposid{sentinel}@;                   // \expos
fixed

2022-02-04 22:52 UTC, jensmaurer commented on source/ranges.tex
> +      using @\exposid{InnerConstRng}@ = range_reference_t<const V>;
removed `\exposid`

2022-02-04 22:59 UTC, JohelEGP requested changes

2022-02-04 22:59 UTC, JohelEGP commented on source/ranges.tex
> +    // \ref{range.join.with.sentinel}, class \tcode{join_with_view::\exposid{sentinel}}
```suggestion
    // \ref{range.join.with.iterator}, class template \tcode{join_with_view::\exposid{iterator}}
    template<bool Const> struct @\exposid{iterator}@;                   // \expos
    // \ref{range.join.with.sentinel}, class template \tcode{join_with_view::\exposid{sentinel}}
```

2022-02-04 22:59 UTC, JohelEGP commented on source/ranges.tex
> +                    @\libconcept{common_range}@<const V> && common_range<@\exposid{InnerConstRng}@>)
```suggestion
      if constexpr (@\libconcept{forward_range}@<const V> && @\libconcept{forward_range}@<@InnerConstRng> &&
                    @\libconcept{common_range}@<const V> && common_range<InnerConstRng>)
```

2022-02-20 16:22 UTC, merged