P2443R1 views::chunk_by
cplusplus/draft pull request #5252
Opened 2022-02-06 08:14 UTC by jensmaurer

2022-02-06 09:52 UTC, JohelEGP requested changes

2022-02-06 09:52 UTC, JohelEGP commented on source/ranges.tex
> +splits the \libconcept{view} into subranges
This is what the paper suggests, and is used elsewhere:
> splits the \libconcept{view} into \tcode{subrange}s on the delimiter.
```suggestion
splits the \libconcept{view} into \tcode{subrange}s
```

2022-02-06 09:52 UTC, JohelEGP commented on source/ranges.tex
> +\end{codeblock}
```suggestion
\end{codeblock}
The above prints: \tcode{[1, 2, 2, 3] [0, 4, 5] [2]}
```

2022-02-06 09:52 UTC, JohelEGP commented on source/ranges.tex
> +  class chunk_by_view : public view_interface<chunk_by_view<V, Pred>>{
```suggestion
  class chunk_by_view : public view_interface<chunk_by_view<V, Pred>> {
```

2022-02-06 09:52 UTC, JohelEGP commented on source/ranges.tex
> +@\exposid{pred_}@ with \tcode{std::move(pred)}.
```suggestion
\exposid{pred_} with \tcode{std::move(pred)}.
```

2022-02-06 09:52 UTC, JohelEGP commented on source/ranges.tex
> +\begin{itemdecl}
```suggestion
\indexlibrarymember{pred}{chunk_by_view}%
\begin{itemdecl}
```

2022-02-06 09:52 UTC, JohelEGP commented on source/ranges.tex
> +constexpr iterator begin();
```suggestion
constexpr @\exposid{iterator}@ begin();
```

2022-02-06 09:52 UTC, JohelEGP commented on source/ranges.tex
> +the amortized constant-time complexity required by the range concept,
```suggestion
the amortized constant-time complexity required by the \libconcept{range} concept,
```

2022-02-06 09:52 UTC, JohelEGP commented on source/ranges.tex
> +An \exposid{iterator} \tcode{i}
```suggestion
An iterator \tcode{i}
```

2022-02-06 09:52 UTC, JohelEGP commented on source/ranges.tex
> +\tcode{ranges::adjacent_find(i, current, not_fn(ref(*\exposid{pred_})))} is equal to \exposid{current}; and
```suggestion
\tcode{ranges::adjacent_find(i, current, not_fn(ref(*\exposid{pred_})))} is equal to \tcode{current}; and
```

2022-02-06 13:17 UTC, JohelEGP commented on source/ranges.tex
> +\begin{itemdecl}
I just happened to notice that all other `pred` were indexed like this.

2022-02-20 22:33 UTC, tkoeppe commented on source/ranges.tex
> +Equivalent to:
@jensmaurer: What is the purpose of this edit?

2022-02-20 22:55 UTC, merged