P0627R6 Function to mark unreachable code
cplusplus/draft pull request #5279
Opened 2022-02-09 16:34 UTC by jensmaurer

Fixes #5263
Fixes cplusplus/papers#275

2022-02-09 16:53 UTC, JohelEGP requested changes

2022-02-09 16:53 UTC, JohelEGP commented on source/utilities.tex
> +\rSec2[utility.unreachable]{Function \tcode{unreachable}}
Why not similarly place the declaration after `underlying_to`?

2022-02-09 16:53 UTC, JohelEGP commented on source/utilities.tex
> +int a = f(1);           // OK; a has value \tcode{1}
```suggestion
int a = f(1);           // OK, \tcode{a} has value \tcode{1}
```

2022-02-11 13:01 UTC, jwakely approved these changes

2022-02-19 20:58 UTC, merged