P2531R0 C++ Standard Library Issues
cplusplus/draft pull request #5288
Opened 2022-02-11 00:17 UTC by jensmaurer

Fixes #5260

2022-02-11 01:02 UTC, JohelEGP requested changes

2022-02-11 17:08 UTC, jensmaurer commented on source/diagnostics.tex
> +the function returns \tcode{error_condition(pxv, generic_category())}.
Because I get a LaTeX overfull `\hbox` otherwise.

2022-02-11 18:28 UTC, JohelEGP commented on source/diagnostics.tex
> +the function returns \tcode{error_condition(pxv, generic_category())}.
So they are equivalent anyways? [ab45510](https://github.com/cplusplus/draft/pull/5288/commits/ab45510119f3749bb0b6900a94895e4a6fe929cb) changes it as the issue requests, just for [2b58d30](https://github.com/cplusplus/draft/pull/5288/commits/2b58d30a4240944758446463a6312732887542b4) to change it to something else.

Searching for `pxv` either in https://cplusplus.github.io/LWG/issue3598 or the sources in the `main` branch has no hits. Perhaps you meant to introduce it here?

2022-02-11 20:35 UTC, jensmaurer commented on source/diagnostics.tex
> +the function returns \tcode{error_condition(pxv, generic_category())}.
First of all, there was a duplicate commit title. This was just wrong; I've squashed it appropriately.

Second, this very phrase introduces posv / pxv and uses that term a few words later. It's never used again, so we can pick any name. It just happens that the edits in the LWG issue caused LaTeX mayhem, so renaming posv to something slightly shorter was the easiest option.

2022-02-11 22:19 UTC, JohelEGP commented on source/diagnostics.tex
> +the function returns \tcode{error_condition(pxv, generic_category())}.
> Second, this very phrase introduces posv / pxv and uses that term a few words later. [...]

That makes sense. I don't know this component, so it wasn't obvious to me it was being introduced. I simply assumed it was referring to an existing `errno` value. Had I looked up `posv`, I would've figured that out. Sorry for the noise.

2022-02-19 15:08 UTC, tkoeppe commented
@jensmaurer: is there a commit for LWG 3616? Or is that superceded by some later issue?

2022-02-19 15:23 UTC, tkoeppe commented
Ah, looks like this has already been handled in 8753efabbbfec8371a82de1af60337fa6a6b6dc2.

2022-02-19 16:12 UTC, merged