Fixed wording regarding omitting the template argument list <>
cplusplus/draft pull request #5512
Opened 2022-06-07 19:53 UTC by ranaanoop

I was reading [temp.arg.explicit] and noticed that there may be some defect in the wording there. In particular, it currently says:

" Trailing template arguments that can be deduced or obtained from default template-arguments may be omitted from the list of explicit template-arguments.

A trailing template parameter pack ([temp.variadic]) not otherwise deduced will be deduced as an empty sequence of template arguments.

If all of the template arguments can be deduced, they may all be omitted; in this case, the empty template argument list <> itself may also be omitted. "

(emphasis mine)

Note carefully, in the last statement it says that when all of the template arguments can be deduced then they may all be omitted and in this case the empty <> itself may also be omitted. This is an issue because it does not mention that we can also omit the empty <> when all of the template arguments can be obtained from the default template arguments.  Since deducing arguments and using default values are two different things, there should be a separate mention of the latter.

Only in the first sentence(quoted above) there is a mention of default template arguments but that is only in the context of the list of explicit template arguments.

This also means that according to the current wording(sentence 3 quoted above) the following should be invalid:

```
template<typename T = int>
void func()
{

}
int main()
{
    func(); //this should be invalid according to the current wording
}
```

But we know that the above is not invalid and so there should be changes made to the sentence 3 quoted above to include the case of default template arguments.

2022-06-07 20:04 UTC, jensmaurer commented
Looks good to me.
Note for later: The commit message needs fixing.

@zygoloid , what do you think?

2022-06-08 13:29 UTC, JohelEGP requested changes

2022-06-08 13:29 UTC, JohelEGP commented on source/templates.tex
> +    auto b = func;              //OK: \tcode{b} has type void (*)(int)
```suggestion
    func();                     // calls the specialization \tcode{func<int>}
    auto a = func<>;            // \tcode{a} has type \tcode{void (*)(int)}
    auto b = func;              // OK: \tcode{b} has type \tcode{void (*)(int)}
```

2022-06-08 19:31 UTC, Quuxplusone reviewed
I originally suggested @ranaanoop submit this as an editorial change; but since it's now been revealed that out of GCC/Clang/MSVC, _only GCC_ actually implements the example's behavior correctly, sadly I now think this is non-editorial and at least a CWG issue if not a full-on paper. I don't think "adding an example, for a long-standing language feature, on which Clang and MSVC currently fail" can possibly be editorial in nature.

2022-06-09 04:19 UTC, ranaanoop commented on source/templates.tex
> +    func();                     // calls the specialization \tcode{func<int>}
Yes, i missed that `func()` wouldn't work as we're not passing any function argument. So I am adding a default function argument as you suggested `void func(T=T{})`

2022-06-09 04:48 UTC, ranaanoop commented on source/templates.tex
> +    func();                     // calls the specialization \tcode{func<int>}
@Quuxplusone Just to confirm, you're suggesting the CWG only for the added example right? The [revised wording](https://github.com/cplusplus/draft/pull/5512/files) is fine and is indeed an editorial fix.

2022-06-09 15:29 UTC, ranaanoop commented
@jensmaurer As can be seen [here](https://godbolt.org/z/hddT6Kh88) all(gcc/clang/msvc) reject the third statement `auto b = f;`.

2022-06-09 16:03 UTC, Quuxplusone commented
> @jensmaurer As can be seen [here](https://godbolt.org/z/hddT6Kh88) all(gcc/clang/msvc) currently reject the statement `auto b = f;`.

Oh that's fun. It looks like GCC accepts the example `auto b = f;` only if `f<>`'s parameter list is composed entirely of non-dependent types. https://godbolt.org/z/EefdTYz6T

2022-07-09 06:15 UTC, jensmaurer commented
I've created CWG2608.

2022-08-19 06:58 UTC, Mick235711 commented
Fixed by #5664.

2022-08-19 08:28 UTC, closed without merging