P2322R6 ranges::fold
cplusplus/draft pull request #5645
Opened 2022-07-24 18:10 UTC by jensmaurer

Fixes #5604
Fixes cplusplus/papers#1004

2022-07-24 19:46 UTC, JohelEGP requested changes

2022-07-24 19:46 UTC, JohelEGP commented on source/algorithms.tex
> +      requires constructible_from<iter_value_t<I>, iter_reference_t<I>>
```suggestion
      @\exposconcept{indirectly-binary-right-foldable}@<iter_value_t<I>, I> F>
      requires @\libconcept{constructible_from}@<iter_value_t<I>, iter_reference_t<I>>
```

2022-07-24 19:46 UTC, JohelEGP commented on source/algorithms.tex
> +    template <@\libconcept{input_range}@ R, @\exposconcept{indirectly-binary-left-foldable}@<range_value_t<R>, iterator_t<R>> F>
Replace all `template <` with `template<`.

2022-07-24 19:46 UTC, JohelEGP commented on source/algorithms.tex
> +  constexpr @\seebelow@ fold_left_with_iter(I first, S last, T init, F f);
```suggestion
  constexpr @\seebelow@ ranges::fold_left_with_iter(I first, S last, T init, F f);
```

2022-07-24 19:46 UTC, JohelEGP commented on source/algorithms.tex
> +  constexpr @\seebelow@ fold_left_with_iter(R&& r, T init, F f);
```suggestion
  constexpr @\seebelow@ ranges::fold_left_with_iter(R&& r, T init, F f);
```

2022-07-24 19:46 UTC, JohelEGP commented on source/algorithms.tex
> +  constexpr @\seebelow@ fold_left_first_with_iter(I first, S last, F f)
```suggestion
  constexpr @\seebelow@ ranges::fold_left_first_with_iter(I first, S last, F f);
```

2022-07-24 19:46 UTC, JohelEGP commented on source/algorithms.tex
> +  constexpr @\seebelow@ fold_left_first_with_iter(R&& r, F f);
```suggestion
  constexpr @\seebelow@ ranges::fold_left_first_with_iter(R&& r, F f);
```

2022-08-04 07:10 UTC, jensmaurer commented on source/algorithms.tex
> +    template <@\libconcept{input_range}@ R, @\exposconcept{indirectly-binary-left-foldable}@<range_value_t<R>, iterator_t<R>> F>
fixed

2022-08-04 14:15 UTC, JohelEGP requested changes

2022-08-04 14:15 UTC, JohelEGP commented on source/algorithms.tex
> +<<<<<<< Updated upstream
```suggestion
```

2022-08-04 14:15 UTC, JohelEGP commented on source/algorithms.tex
> +>>>>>>> Stashed changes
```suggestion
```

2022-08-16 21:37 UTC, merged