P2438R2 std::string::substr() &&
cplusplus/draft pull request #5678
Opened 2022-07-28 21:33 UTC by jensmaurer

Fixes #5611
Fixes cplusplus/papers#1104

2022-07-28 22:41 UTC, JohelEGP requested changes

2022-07-28 22:41 UTC, JohelEGP commented on source/compatibility.tex
> +assert(s1 == s2);       // unspecified, previously guaranteed to be true
```suggestion
assert(s1 == s2);       // unspecified, previously guaranteed to be \tcode{true}
```

2022-07-28 22:41 UTC, JohelEGP commented on source/compatibility.tex
> +assert(s1 == s2);       // unspecified, previously guaranteed to be true
```suggestion
assert(s1 == s2);       // unspecified, previously guaranteed to be \tcode{true}
```

2022-08-03 16:00 UTC, jwakely submitted a review, later dismissed
I agree that `true` should use code font, otherwise this looks correct.

2022-08-17 12:25 UTC, merged