P2291R3 Add Constexpr Modifiers to Functions to_chars and from_chars for Integral Types in <charconv> Header
cplusplus/draft pull request #5697
Opened 2022-07-31 19:43 UTC by jensmaurer

Fixes #5602
Fixes cplusplus/papers#984

2022-07-31 21:34 UTC, JohelEGP requested changes

2022-07-31 21:34 UTC, JohelEGP commented on source/support.tex
> +#define @\defnlibxname{cpp_lib_constexpr_charconv}@                202207L // also in \libheader{charconv}
```suggestion
#define @\defnlibxname{cpp_lib_constexpr_charconv}@                202207L // also in \libheader{charconv}
#define @\defnlibxname{cpp_lib_constexpr_cmath}@                   202202L // also in \libheader{cmath}, \libheader{cstdlib}
```

2022-08-03 15:47 UTC, jwakely submitted a review, later dismissed
The feature test macro should be in alphabetical order, but otherwise this looks correct.

2022-08-16 16:39 UTC, tkoeppe commented
Fixed by 0a9cfa5865fec5beecd14e0c369ca6deace84044.

2022-08-16 16:39 UTC, closed without merging