[range.cartesian.view] Fix complete neglect for parent_
cplusplus/draft pull request #5770
Opened 2022-08-22 04:54 UTC by hewillk

2022-08-22 11:07 UTC, tkoeppe commented
@jwakely Does this require an LWG issue?

2022-08-22 12:51 UTC, hewillk commented
If this is the LWG, there is *no* way to implement a functional `cartesian_view` according to the draft until the LWG makes any decisions.

2022-08-22 13:10 UTC, tkoeppe commented
> If this is the LWG, there is _no_ way to implement a functional `cartesian_view` according to the draft until the LWG makes any decisions.

That may well be so, but is not an editorial concern.

`vector` also wasn't implementable until C++23, but that also didn't get fixed editorially.

2022-08-22 15:30 UTC, jwakely requested changes
Use semantic line breaks:
https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines#latex-source-code-formatting

2022-08-22 15:30 UTC, jwakely commented on source/ranges.tex
> +Initializes \exposid{parent_} with \tcode{addressof(parent)} and \exposid{current_} with \tcode{std::move(current)}.
```suggestion
Initializes \exposid{parent_} with \tcode{addressof(parent)}
and \exposid{current_} with \tcode{std::move(current)}.
```

2022-08-22 15:30 UTC, jwakely commented on source/ranges.tex
> +Initializes \exposid{parent_} with \tcode{i.\exposid{parent_}} and \exposid{current_} with \tcode{std::move(i.\exposid{current_})}.
```suggestion
Initializes \exposid{parent_} with \tcode{i.\exposid{parent_}}
and \exposid{current_} with \tcode{std::move(i.\exposid{current_})}.
```

2022-08-22 15:31 UTC, jwakely commented
> If this is the LWG, there is _no_ way to implement a functional `cartesian_view` according to the draft until the LWG makes any decisions.

That's fine. This is not a final standard, there is no great urgency to fix defects in a draft.

Implementors can easily do this without waiting for an LWG decision. It's common that we implement fixes before they make it into the draft.

Although the changes here seem correct, I don't think it's editorial. Please submit an LWG issue instead, thanks!

2022-08-22 16:53 UTC, tkoeppe commented
Could you kindly edit the pull request to avoid sounding disparaging of the existing work and the people who have contributed it?

2022-08-22 17:01 UTC, hewillk commented
@tkoeppe  Sorry for the misunderstanding caused by the misuse of words, I will be more careful with words in the future pull.

@jwakely, thanks for the suggestion.
The reason I insist this is an editorial fix is that it was clearly an oversight, and I believe the fix was what the author originally intended. Maybe we can ask the author again about this opinion after he is on vacation.

If this is definitely an LWG, I'd like to ask _when_ it would be appropriate to submit it to the LWG, as the C++23 draft hasn't been published yet.

2022-08-22 17:08 UTC, jensmaurer commented
Specifically addressing your question, you should submit an issue to lwgchair now, so that the matter does not get lost.

2022-08-23 05:43 UTC, closed without merging

2022-08-23 05:46 UTC, hewillk commented
Closed and intends to submit LWG for this.