[ranges] Improve examples
cplusplus/draft pull request #5791
Opened 2022-08-24 17:14 UTC by hewillk

1. Use `views::istream` instead of `ranges::istream_view` (consistent with #4659).
2. Remove unnecessary `std::` qualification.

2022-08-24 17:22 UTC, hewillk commented
Hmm, how do I make these comments align?

2022-08-24 17:32 UTC, JohelEGP requested changes
Removing `std::` removes 5 characters. Add 1 space so the comment is aligned to a multiple of 4.

2022-08-24 17:32 UTC, JohelEGP commented on source/ranges.tex
> +    co_yield ranges::elements_of(r);       // yield each element of \tcode{r}
```suggestion
    co_yield ranges::elements_of(r);        // yield each element of \tcode{r}
```

2022-08-24 17:32 UTC, JohelEGP commented on source/ranges.tex
> +    co_yield r;                            // yield \tcode{r} as a single value
```suggestion
    co_yield r;                             // yield \tcode{r} as a single value
```

2022-08-24 17:32 UTC, JohelEGP commented on source/ranges.tex
> +    cout << i << ' ';      // prints \tcode{0 1 2}
```suggestion
    cout << i << ' ';       // prints \tcode{0 1 2}
```

2022-08-24 17:42 UTC, hewillk commented
You are my lifesaver, thanks.

2022-08-24 18:43 UTC, jensmaurer approved these changes
Looks good.

2022-08-25 09:14 UTC, jwakely approved these changes

2022-08-25 11:31 UTC, merged