[basic.life]/8.3 don't put const in the middle of "complete object" words of power
cplusplus/draft pull request #5818
Opened 2022-09-08 13:39 UTC by RedBeard0531

"Complete object" is a defined term (https://eel.is/c++draft/basic#def:complete_object). Putting const in the middle of that makes it unclear if we are referring to a const-qualified "complete object" or a complete const object with some other meaning of "complete" such as "with a complete type". Using the order "const complete object" avoids that ambiguity. It also matches the word order used in https://eel.is/c++draft/basic.life#10 to make it UB to create a new object on top of a "const complete object", unless it has dynamic storage duration.

2022-09-08 14:03 UTC, jwakely reviewed
Would "complete object of const type" be even better?

2022-09-08 19:08 UTC, jensmaurer commented
@RedBeard0531, turning your argument around, [basic.type.qualifier] p1.1 defines "const object". We shouldn't put "complete" in the middle of a defined term.

Having said, that "const complete object" sounds a little better than the existing phrasing.

2022-09-08 19:08 UTC, jensmaurer approved these changes

2022-09-08 19:33 UTC, tkoeppe commented
How about "const, complete object" or "complete, const object"? Constness and completeness are both separate qualifications of "object", right? Constness does not only appertain to complete objects, nor does completeness to const objects?

2022-09-14 20:20 UTC, tkoeppe commented
@jwakely, @RedBeard0531 Could you please take another look?

2022-09-14 22:12 UTC, jwakely commented
I like the suggestion to put a comma there. Of the two, I have a weak preference for "const, complete object".

2022-09-15 08:44 UTC, RedBeard0531 commented
"const, complete object" sounds good to me too. Should we also update [basic.life]/10 to match?

> Constness does not only appertain to complete objects, nor does completeness to const objects?

The line that this PR is modifying does mean that in some sense constness only "really" means anything on a complete object, since const subobjects of non-const objects can still be overwritten. But that doesn't change the fact that non-complete objects can also be marked as const, with the effects on overload resolution and such.

2022-09-16 11:43 UTC, jensmaurer requested changes
Could we please add the comma and then move on with this trivial pull request?

2022-09-16 15:38 UTC, jensmaurer approved these changes

2022-09-16 15:38 UTC, jensmaurer commented
This seems to do what we wanted.

2022-09-16 15:46 UTC, merged