Update references to Unicode Standard & Annexes.
cplusplus/draft pull request #5826
Opened 2022-09-14 01:44 UTC by cor3ntin

Currently we have a normative reference to ISO 10646 (Unicode 13.0), a floating normative reference to UAX44 (= Unicode 15.0), bibligraphy items for Unicode (14.0),
text segmentation UAX (12.0), and identifier syntax (13.0).

This align the bibligraphy items and mentions of Unicode to refer to 15.0.

Mention of Unicode 14 in the specification of print are also updated to refer to Unicode 15.

No further changes are necessary to comply to the updated standard and annexes.

2022-09-14 01:46 UTC, JohelEGP requested changes

2022-09-14 01:46 UTC, JohelEGP commented on source/back.tex
> +  2022-08-31 [viewed 	2022-09-14].
```suggestion
  2022-08-31 [viewed 2022-09-14].
```

2022-09-14 04:40 UTC, jensmaurer commented
For the bibliography references, I'd like CWG and/or LWG review / approval that we're still good with the semantics described in the updated version. (Alternatively, some review in the editorial group that Unicode did at most editorial updates to the relevant sections.)

For the references in iostreams.tex, we should instead refer to ISO 10646 and avoid the numerical section references (because it may change when updates are published).

2022-09-14 08:13 UTC, jwakely commented
I agree with Jens, changing the references is not just editorial.

2022-09-14 09:05 UTC, cor3ntin commented
> For the bibliography references, I'd like CWG and/or LWG review / approval that we're still good with the semantics described in the updated version. (Alternatively, some review in the editorial group that Unicode did at most editorial updates to the relevant sections.)
 
> For the references in iostreams.tex, we should instead refer to ISO 10646 and avoid the numerical section references (because it may change when updates are published).

But this is not a behavior described by ISO 10646. References in Unicode do not happen to change very often. I'd have not objection to remove the numerical reference though

2022-09-14 12:53 UTC, cor3ntin commented
If someone wants to put that diff in html and then back again, please feel
free to do so.

Otherwise I'll make a NB comment so that we don't loose track of it.

Cheers.

On Wed, Sep 14, 2022, 14:47 Thomas Köppe ***@***.***> wrote:

> In any case, it looks like we want an LWG issue here. Can we close the
> editorial issue?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cplusplus/draft/pull/5826#issuecomment-1246714129>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKX763EN4TLCUAQJPXDTKLV6HCMJANCNFSM6AAAAAAQL6THDM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-14 20:19 UTC, tkoeppe commented
Since changing normative references is not editorial, I don't see how it would be appropriate to make this change without WG21 oversight and record keeping. But it sounds like filing an LWG issue would be a bit simpler than filing an NB comment!

2022-09-14 20:19 UTC, closed without merging

2022-09-15 21:56 UTC, jensmaurer commented
@tkoeppe , the bibliography changes are not per se normative (but may still present a larger lever than what we're happy to apply editorially).

2022-11-06 02:53 UTC, JohelEGP commented
> Normatively referenced documents shall be documents published by ISO or IEC. In the absence of appropriate ISO or IEC documents, those published by other bodies may be listed as normative references provided that [...]
> -- [ISO/IEC Directives, Part 2, section 10.2 "Permitted referenced documents"](https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor130)

It seems possible to keep only the undated reference in [intro.refs] if ISO/IEC 10646 is not appropriate due to
> [P]revent[ing] the use of features from newer Unicode Standard releases for up to several years.
> -- https://github.com/cplusplus/nbballot/issues/412#issuecomment-1304696400

2022-11-08 03:59 UTC, tahonermann commented
Thank you, @JohelEGP, that reference is helpful. I agree that we have the ability to reference both in a consistent fashion. That still leaves us with the downsides of 1) requiring us to word the dependency relationship between the two standards, 2) requiring implementors to consult both standards, and 3) resolving any discrepancies that arise between the two standards.

Those downsides aren't exorbitant, but they are complications that would be avoided by solely referring to the Unicode Standard.

2022-11-08 14:10 UTC, JohelEGP commented
If those downsides make the ISO Standard not appropriate, it seems to me that the first quote of https://github.com/cplusplus/draft/pull/5826#issuecomment-1304702217 can be applied to refer only to the Unicode Standard.