P2167R3 Improved Proposed Wording for LWG 2114 (contextually converti…
cplusplus/draft pull request #5986
Opened 2022-11-17 21:30 UTC by jensmaurer

…ble to bool)

Fixes NB US 073 (C++23 CD).

Fixes #5971
Fixes cplusplus/papers#877
Fixes cplusplus/nbballot#504

2022-11-17 22:02 UTC, JohelEGP requested changes

2022-11-17 22:02 UTC, JohelEGP commented on source/threads.tex
> +\exposconcept{boolean-testable}\iref{concept.booleantestable]}.
```suggestion
\exposconcept{boolean-testable}\iref{concept.booleantestable}.
```

2022-11-17 22:38 UTC, jensmaurer commented on source/threads.tex
> +\exposconcept{boolean-testable}\iref{concept.booleantestable]}.
Fixed

2022-11-19 04:21 UTC, burblebee requested changes
2 issues: (1) widen "Return type" column in tables and (2) fix wording for "each [...] models".

2022-11-19 12:21 UTC, Dani-Hub commented on source/support.tex
> +  \exposconcept{boolean-testable},
Can we please keep the "each" regardless the position? My interpretation of a previous review of @W-E-Brown was that the "each" makes the interpretation unambiguous. But maybe Walter would like to correct my possibly incorrect interpretation of his actually words used?

2022-11-19 13:24 UTC, JohelEGP commented on source/support.tex
> +  \exposconcept{boolean-testable},
> and change "models" to "model" ("each" can be either plural or singular in this case, but plural sounds better and I think is what is most often used elsewhere in the spec).

According to https://github.com/cplusplus/draft/pull/5986#discussion_r1025760788, when "each" is next to "model", there are 10 occurrences for "model" and 0 for "models".

2022-11-19 13:43 UTC, W-E-Brown commented
> On Nov 19, 2022, at 6:21 AM, Daniel Krügler ***@***.***> wrote:
> @Dani-Hub commented on this pull request.
> 
> In source/support.tex <https://github.com/cplusplus/draft/pull/5986#discussion_r1027083394>:
> 
> > @@ -5045,7 +5045,9 @@
>    Otherwise, \tcode{strong_order(E, F)} if it is a well-formed expression.
>  \item
>    Otherwise, if the expressions \tcode{E == F} and \tcode{E < F}
> -  are both well-formed and convertible to \tcode{bool},
> +  are both well-formed and
> +  each of \tcode{decltype(E == F)} and \tcode{decltype(E < F)} models
> +  \exposconcept{boolean-testable},
> Can we please keep the "each" regardless the position? My interpretation of a previous review of @W-E-Brown <https://github.com/W-E-Brown> was that the "each" makes the interpretation unambiguous. But maybe Walter would like to correct my possibly incorrect interpretation of his actually words used?
> 
Daniel has the right idea:  The words "each" and "both" are not interchangeable; they mean different things.  The use of "both" in this sentence changes the meaning, leading to an incorrect specification, as was discussed before the wording was approved in committee.

2022-11-19 14:43 UTC, W-E-Brown commented
> On Nov 19, 2022, at 7:24 AM, Johel Ernesto Guerrero Peña ***@***.***> wrote:
> @JohelEGP commented on this pull request.
> 
> In source/support.tex <https://github.com/cplusplus/draft/pull/5986#discussion_r1027089740>:
> 
> > @@ -5045,7 +5045,9 @@
>    Otherwise, \tcode{strong_order(E, F)} if it is a well-formed expression.
>  \item
>    Otherwise, if the expressions \tcode{E == F} and \tcode{E < F}
> -  are both well-formed and convertible to \tcode{bool},
> +  are both well-formed and
> +  each of \tcode{decltype(E == F)} and \tcode{decltype(E < F)} models
> +  \exposconcept{boolean-testable},
> and change "models" to "model" ("each" can be either plural or singular in this case, but plural sounds better and I think is what is most often used elsewhere in the spec).
> 
> According to #5986 (comment) <https://github.com/cplusplus/draft/pull/5986#discussion_r1025760788>, when "each" is next to "model", there are 10 occurrences for "model" and 0 for "models".
> 
Sorry, but for such purposes "next to" appears to be an irrelevant grammatical criterion:  The sole applicable criterion, according to multiple dictionaries and grammar books, is whether the subject of the clause is singular or plural.
In Daniel's "each of ..." wording formulation, above, "each" is a pronoun used as the subject and is clearly singular, so "models" would be correct.
In the formulation "the expressions ... and ... each ...", the use of "each" is adverbial (meaning "individually"), rather than pronominal; this leaves "the expressions" as the plural subject, so "model" would be correct.
(Those above-cited "10 occurrences" should be probably be similarly audited for correctness via analogous analysis.)

2022-11-19 15:40 UTC, JohelEGP commented
> In the formulation "the expressions ... and ... each ...", the use of "each" is adverbial (meaning "individually"), rather than pronominal; this leaves "the expressions" as the plural subject, so "model" would be correct. (Those above-cited "10 occurrences" should be probably be similarly audited for correctness via analogous analysis.)

The 10 occurrences are of the form "`T1` and `T2` each model `C`", so they should be correct.

2022-11-19 15:41 UTC, JohelEGP commented
Here's the actual output:
```cli
$ grep 'each model ' *.tex
algorithms.tex:   \tcode{R1} and \tcode{R2} each model \libconcept{sized_range} and
algorithms.tex:\tcode{R1} and \tcode{R2} each model \libconcept{sized_range}, and
concepts.tex:that each model \exposconcept{boolean-testable-impl},
ranges.tex:  each model \libconceptx{for\-ward_range}{forward_range}, then \tcode{iterator_concept} denotes
ranges.tex:each model \exposconcept{bidirectional-common},
ranges.tex:\exposid{Base} and \exposid{InnerBase} each model \libconcept{forward_range},
ranges.tex:\exposid{Base} and \exposid{InnerBase} each model \libconcept{forward_range}.
ranges.tex:each model \tcode{\libconcept{derived_from}<bidirectional_iterator_category>}
ranges.tex:each model \libconcept{common_range},
ranges.tex:each model \tcode{\libconcept{derived_from}<forward_iterator_tag>},
```

2022-11-19 15:51 UTC, JohelEGP commented on source/utilities.tex
> +For all \tcode{i}, each \tcode{decltype(get<i>(t) == get<i>(u))} models
To clarify, all wording around `tuple` of the form "for each _index_,  _use-of-index_ _description-of-use-of-index_" seem to omit "each".
https://github.com/cplusplus/draft/blob/fb0df97e7d7c2c75bbdf7164c33b0796024ff6d3/source/utilities.tex#L2145-L2146
Likewise for all `tuple`'s `operator=`.
> [2](https://eel.is/c++draft/tuple.rel#2)
[#](http://github.com/Eelis/draft/tree/9a4a02f8a10f75675094dc0f81e089d1751ff3d8/source/utilities.tex#L2900)
Mandates: For all i, where 0≤i<sizeof...(TTypes), get<i>(t) == get<i>(u) is a valid expression returning a type that is convertible to bool[.](https://eel.is/c++draft/tuple.rel#2.sentence-1)
sizeof...(TTypes) equals tuple_­size_­v<UTuple>[.](https://eel.is/c++draft/tuple.rel#2.sentence-2)
> -- https://eel.is/c++draft/tuple.rel#2

2022-11-22 04:08 UTC, burblebee commented
When using "Each of", "each" is singular (so "models" is correct).
When using "x and y each", "each" is plural (so "model" is correct)..
Are there other cases that don't fit either of these patterns?

See https://www.masterclass.com/articles/is-each-singular-or-plural and similar sites.

> (Those above-cited "10 occurrences" should be probably be similarly audited for correctness via analogous analysis.)

They are correct as is.

2022-12-09 13:41 UTC, jwakely commented on source/support.tex
> +  \exposconcept{boolean-testable},
IMHO "decltype(E == F) and decltype(E < F) model boolean-testable" has a very different meaning from "decltype(E == F) and decltype(E < F) each model boolean-testable".

The former means `boolean-testable<decltype(E==F), decltype(E<F)>` and the latter means `boolean_testable<decltype(E==F)> && boolean-testable<decltype(E<F)>` which is very different. The latter is what we want.

2022-12-09 13:48 UTC, jwakely approved these changes
It might be nice if we consistently say **either** "A and B each model C" **or** "each of A and B models C", but the changes as applied are not incorrect. And as I noted in a comment, changing to "A and B model C" would definitely be incorrect, so maybe best not to fiddle with it!

2022-12-15 15:02 UTC, tkoeppe commented on source/utilities.tex
> +For all \tcode{i}, each \tcode{decltype(get<i>(t) == get<i>(u))} models
Thanks, sounds reasonable!

2022-12-15 15:04 UTC, JohelEGP commented on source/utilities.tex
> +For all \tcode{i}, each \tcode{decltype(get<i>(t) == get<i>(u))} models
```suggestion
For all \tcode{i}, \tcode{decltype(get<i>(t) == get<i>(u))} models
```

2022-12-15 15:04 UTC, tkoeppe commented on source/support.tex
> +  \exposconcept{boolean-testable},
Thank you for the discussion! I won't make any changes here, please file separate issues if you think the wording should be improved. This looks subtle, and we should only deviate from previous LWG review with a proper discussion.

2022-12-15 15:05 UTC, JohelEGP commented on source/utilities.tex
> +For all \tcode{i}, each \tcode{decltype(get<i>(t) == get<i>(u))} models
```suggestion
For each \tcode{i}, \tcode{decltype(get<i>(t) == get<i>(u))} models
```

2022-12-15 15:12 UTC, tkoeppe commented on source/utilities.tex
> +For all \tcode{i}, each \tcode{decltype(get<i>(t) == get<i>(u))} models
I'm OK with "for all", that's a fairly common mathematical phrase.

2022-12-15 15:15 UTC, tkoeppe commented on source/lib-intro.tex
> +\tcode{decltype(a == b)} models \exposconceptx{boolean-testa\-ble}{boolean-testable} &
We will replace these tables with @jensmaurer paragraph pattern, so this will not be a problem eventually.

2022-12-15 16:06 UTC, merged