Motions 2023 02 cwg 1
cplusplus/draft pull request #6118
Opened 2023-02-15 17:03 UTC by burblebee

Fixes #6083.

2023-02-17 18:42 UTC, JohelEGP requested changes

2023-02-17 18:42 UTC, JohelEGP commented on source/expressions.tex
> +to unequal function pointers or to unequal pointers to void
```suggestion
to unequal function pointers or to unequal pointers to \tcode{void}
```

2023-02-17 18:42 UTC, JohelEGP commented on source/expressions.tex
> +  it does not have indeterminate value\iref{basic.indet},
#6112 suggests
```suggestion
  it does not have an indeterminate value\iref{basic.indet},
```

2023-02-17 18:42 UTC, JohelEGP commented on source/classes.tex
> +if it is constexpr-suitable\iref{dcl.constexpr}.
I don't see this change from CWG2602:
> Change in 9.5.2 [[dcl.fct.def.default](https://wg21.link/dcl.fct.def.default#3)] paragraph 3 as follows:
>
>    A function explicitly defaulted on its first declaration is implicitly inline (9.2.8 [[dcl.inline](https://wg21.link/dcl.inline)]), and is implicitly constexpr (9.2.6 [[dcl.constexpr](https://wg21.link/dcl.constexpr)]) if it satisfies the requirements for a constexpr function is constexpr-suitable.

2023-02-21 21:45 UTC, burblebee commented on source/expressions.tex
> +to unequal function pointers or to unequal pointers to void
done, thanks!

2023-02-22 22:57 UTC, JohelEGP approved these changes
Also resolves #6112.

2023-03-05 17:12 UTC, merged