[LWG 5] P2770R0 Stashing stashing iterators for proper flattening
cplusplus/draft pull request #6128
Opened 2023-02-16 03:49 UTC by burblebee

Fixes NB US 61-126 (C++23 CD).

Fixes #6095.

2023-02-21 19:35 UTC, JohelEGP requested changes

2023-02-21 19:35 UTC, JohelEGP commented on source/ranges.tex
> +  return *@\exposid{as-lvalue}@(@\exposid{outer}@());
```suggestion
  return @\exposid{as-lvalue}@(*@\exposid{outer}@());
```

2023-02-21 19:35 UTC, JohelEGP commented on source/ranges.tex
> +  return *@\exposid{as-lvalue}@(@\exposid{outer}@());
```suggestion
  return @\exposid{as-lvalue}@(*@\exposid{outer}@());
```

2023-02-21 19:35 UTC, JohelEGP commented on source/ranges.tex
> +  requires (!@\libconcept{forward_range}@<@\exposid{Base}@>);;
```suggestion
  requires (!@\libconcept{forward_range}@<@\exposid{Base}@>);
```

2023-02-22 00:10 UTC, burblebee commented on source/ranges.tex
> +                                                                // if \tcode{\exposid{Base}} models \libconcept{forward_range}
FWIW, we use this formatting elsewhere in comments like this, but you're right, that's no reason to replicate that here just for the sake of consistency :). Fixed.

2023-02-22 00:16 UTC, burblebee commented on source/ranges.tex
> +  return *@\exposid{as-lvalue}@(@\exposid{outer}@());
Thanks!

2023-02-22 00:16 UTC, burblebee commented on source/ranges.tex
> +  return *@\exposid{as-lvalue}@(@\exposid{outer}@());
thanks!

2023-02-23 02:41 UTC, JohelEGP commented on source/ranges.tex
> +                                                                // if \tcode{\exposid{Base}} models \libconcept{forward_range}
A check for this should be easy @jensmaurer.

2023-02-23 02:44 UTC, JohelEGP approved these changes

2023-03-07 22:24 UTC, merged