[LWG 15] P2655R3 common_reference_t of reference_wrapper Should Be a Reference…
cplusplus/draft pull request #6131
Opened 2023-02-16 23:49 UTC by burblebee

[refwrap.common.ref] Enclose code in namespace std for consistency.

Fixes #6105.

2023-02-21 15:48 UTC, hewillk commented on source/utilities.tex
> +    inline constexpr bool @\exposid{is-ref-wrapper}@<reference_wrapper<T>> = true;
```suggestion
  template<class T>
    constexpr bool @\exposid{is-ref-wrapper}@ = false;                       // \expos

  template<class T>
    constexpr bool @\exposid{is-ref-wrapper}@<reference_wrapper<T>> = true;
```

2023-02-21 15:51 UTC, hewillk commented on source/utilities.tex
> +    inline constexpr bool @\exposid{is-ref-wrapper}@<reference_wrapper<T>> = true;
see #4625.

2023-02-22 03:21 UTC, burblebee commented on source/utilities.tex
> +    inline constexpr bool @\exposid{is-ref-wrapper}@<reference_wrapper<T>> = true;
Thanks! Fixed.

2023-02-22 03:25 UTC, hewillk approved these changes

2023-02-23 13:23 UTC, JohelEGP requested changes

2023-02-23 13:23 UTC, JohelEGP commented on source/utilities.tex
> +             !@\exposconcept{ref-wrap-common-reference-exists-with}@<T, R, TQual<T>, RQual<R>>)
```suggestion
    requires (@\exposconcept{ref-wrap-common-reference-exists-with}@<R, T, RQual<R>, TQual<T>> &&
              !@\exposconcept{ref-wrap-common-reference-exists-with}@<T, R, TQual<T>, RQual<R>>)
```
See #4720.

2023-02-23 13:23 UTC, JohelEGP commented on source/utilities.tex
> +             !@\exposconcept{ref-wrap-common-reference-exists-with}@<T, R, TQual<T>, RQual<R>>)
```suggestion
    requires (@\exposconcept{ref-wrap-common-reference-exists-with}@<R, T, RQual<R>, TQual<T>> &&
              !@\exposconcept{ref-wrap-common-reference-exists-with}@<T, R, TQual<T>, RQual<R>>)
```
See #4720.

2023-02-28 05:07 UTC, burblebee commented on source/utilities.tex
> +             !@\exposconcept{ref-wrap-common-reference-exists-with}@<T, R, TQual<T>, RQual<R>>)
thanks! done

2023-02-28 13:10 UTC, JohelEGP approved these changes

2023-03-11 20:44 UTC, merged