P2588R3 barrier's phase completion guarantees
cplusplus/draft pull request #6142
Opened 2023-02-20 21:39 UTC by jensmaurer

Fixes #6109 
Fixes cplusplus/papers#1246 
Fixes cplusplus/nbballot#541
Fixes cplusplus/nbballot#468

2023-02-22 18:40 UTC, JohelEGP requested changes

2023-02-22 18:40 UTC, JohelEGP commented on source/compatibility.tex
> +\rSec2[diff.cpp20.thread]{\ref{thread}: threads library}
```suggestion
\rSec2[diff.cpp20.thread]{\ref{thread}: concurrency support library}
```

2023-02-22 21:09 UTC, jensmaurer commented on source/compatibility.tex
> +\rSec2[diff.cpp20.thread]{\ref{thread}: threads library}
Fixed

2023-02-23 03:19 UTC, JohelEGP approved these changes

2023-03-12 11:41 UTC, merged