Prevent double spacing in tcode
cplusplus/draft pull request #6200
Opened 2023-03-21 11:34 UTC by morinmorin

Due to `nofrenchspacing`, a space after `.`, `:`, `?` are rendered as two spaces in monospaced fonts if these punctuations are preceded by non-capital characters. For example, `\tcode{a ? b : c}` is rendered as `a ?  b :  c
`
and
```
\tcode{template <class... A> void f(A...) noexcept}
```
is rendered as
```
template <class...  A> void f(A...)  noexcept;
```

Currently, there are tens of these double spacings in the Standard.
This PR prevents them by adding `\frenchspacing` to `CodeStylex`.

2023-03-21 11:39 UTC, morinmorin commented
Diff screenshot.
![frenchspacing](https://user-images.githubusercontent.com/2411812/226595439-b5b8c2fb-bd61-437c-b0f5-8996eba43d66.png)

2023-03-21 12:01 UTC, morinmorin commented
Defining `\tcode` using `\lstinline` would be far better. Benefits of `\lstinline` include

- Single quotes are rendered as straight quotes (using `upquote` option).
- No escape is needed; we can just write `%`, `\`, etc.
- No double spacings.

`\lstinline` can be used with `mathescape` option. So we can use macros in `$...$` e.g. `using $\exposidnc{indirect-value-t}$ = $\seebelow$`.

However, **`\lstinline` behaves badly when used in macro arguments**. For example, backslashes are used as escape characters in the TeX world and spaces before `$` are not rendered.

2023-03-24 06:25 UTC, jensmaurer commented
This now has overfull `\hbox` issues that need to be addressed.

2023-03-24 06:25 UTC, jensmaurer requested changes
Please fix overfull lines per "check-output.sh" results.

2023-03-26 23:26 UTC, morinmorin commented
Thanks for the guidance. There are three overfull boxes.

- `ranges.tex (L10873–10878, std.pdf: p. 1225+10): 0.32013pt too wide`
  * The offending word: `\tcode{iterator_category}`.
  * The overfullness is so small. This “overfull hbox” warning is suppressed by locally increasing `\hfuzz` from `0.1pt` (the default value) to `0.5pt` (this value is also used in `\sloppy`). Note that “overfull hbox” warnings are emitted only when the width is more than `\hfuzz`'s value. 

- `ranges.tex (L15112–15116, std.pdf: p. 1262+10): 141.33292pt too wide`
  * The offending “word”: `\tcode{… ? … : …}`
  * Easily fixable. It is fixed by adding `\brk` after `: `.

- `iostreams.tex (L2279–2287 std.pdf: p. 1628+10): 21.81808pt too wide`
  * The offending word: "implementation-defined" emitted from `\impldef`.
  * TeX does not hyphenate words that already contain hyphens (compound words). Adding `\-` changes this behavior. Compound words might be better not to be hyphenated, so I add `\-` conservatively (i.e. `imple\-men\-ta\-tion-defined` rather than `im\-ple\-men\-ta\-tion-de\-fined`). 

The global macro `\impldef` is changed in the third one, which introduces changes like "implementation-defined" -> "implementa-tion-defined" in other places.

2023-03-26 23:31 UTC, morinmorin commented
A screenshot for the first overfull hbox (`iterator_-`).
![iterator_category](https://user-images.githubusercontent.com/2411812/227811690-3ee10c90-0d8f-498c-a675-0449385e490a.png)

2023-03-27 07:11 UTC, jensmaurer commented
For the first transgression, can you add a hyphenation hint iterator_catego\-ry instead? Usually, the spaces are already very compressed when you get an overfull \hbox warning, and we regularly hyphenate this \tcode words if necessary.

2023-03-27 09:05 UTC, morinmorin commented
For the first transgression, the offending part is the `-` just after the highlighted "tor_" in the screenshot. `\tcode{it\-er\-a\-tor_cat\-e\-go\-ry}` doesn't make any change in the output.

The only viable hyphen-hint is `\tcode{iterator\-_category}`, which outputs "iterator-`\n`_category". Is this our preferred option?

2023-03-28 23:13 UTC, morinmorin commented
I took this route: 

> `\tcode{iterator\-_category}`

The issue is resolved now, I think.

2023-03-29 15:30 UTC, jensmaurer commented
@tkoeppe, this looks like an editorial improvement.

2023-04-30 12:23 UTC, tkoeppe commented
@jensmaurer Yes, I agree. Any final thoughts?

2023-04-30 18:26 UTC, jensmaurer approved these changes
Fine with me.

2023-05-10 11:16 UTC, merged