[defns.dynamic.type] Say "most derived object" in the example
cplusplus/draft pull request #6203
Opened 2023-03-23 03:07 UTC by frederick-vs-ja

and
- don't say the static type of a pointer, because the difference between static and dynamic types is only present for glvalues of class types;
- say that the `B*` pointer is pointing to a `B` base class subobject, which avoids involving problematic cases of `reinterpret_cast` or `static_cast` from _cv_ `void*` (see [[expr.static.cast]/14](https://eel.is/c++draft/expr.static.cast#14)).

Fixes #5762.
Fixes cplusplus/CWG#257.

2023-03-23 13:27 UTC, JohelEGP requested changes

2023-03-23 13:27 UTC, JohelEGP commented on source/intro.tex
> +class \tcode{B}'' is pointing to a base class subobject class object
Seems unintentional.
```suggestion
class \tcode{B}'' is pointing to a base class subobject
```

2023-03-23 17:36 UTC, frederick-vs-ja commented on source/intro.tex
> +class \tcode{B}'' is pointing to a base class subobject class object
Thank you for correction!

2025-06-17 14:17 UTC, tkoeppe commented
@jensmaurer: Could you have a look?

2025-06-17 16:47 UTC, merged