[container.opt.reqmts] Index 3-way compare for containers
cplusplus/draft pull request #6220
Opened 2023-04-04 16:41 UTC by AlisdairM

All of the standard containers are 3-way comparable, but the specification is provided under optional container requirements so does not show up in the index.

Adding these links shows just how poorly indexed the members of the 'flat_*' container adapters are, but that is properly the business on a separate PR.

2023-04-04 16:45 UTC, JohelEGP requested changes

2023-04-04 16:45 UTC, JohelEGP commented on source/containers.tex
> +\indexlibrarymember{unordered_multimap}{operator<=>}%
```suggestion
\indexcont{operator<=>}%
```

2023-04-04 16:48 UTC, JohelEGP commented on source/containers.tex
> +\indexlibrarymember{unordered_multimap}{operator<=>}%
Readded `forward_list`.

2023-04-04 16:54 UTC, JohelEGP commented on source/containers.tex
> +\indexlibrarymember{unordered_multimap}{operator<=>}%
The difference is that `\indexcont` uses `\indexlibrarymemberx`, which only adds the member under the container, rather than both ways.

2023-04-04 17:32 UTC, AlisdairM commented
I think we now have two options: the original version of the PR, or the current state where I use a local macro to index all operations with a grouped text-name, while retaining the correct indexing in each container.

@tkoeppe @jensmaurer @jwakely could you express a preference?

2023-04-04 18:21 UTC, JohelEGP requested changes

2023-04-12 20:32 UTC, jensmaurer commented
The current state with `\indexcont` seems what we do elsewhere in the container requirements sections, so I'd say "squash and merge" as-is.

2023-11-08 02:38 UTC, tkoeppe commented
@jwakely Any thoughts?

2023-11-08 11:47 UTC, jwakely commented on source/containers.tex
> +% Local command to index names as members of all containers.
I don't have a preference on which way to do this, but I would prefer:

```suggestion
% Local command to index a name as a member of all containers.
```

2023-11-08 15:55 UTC, merged