P2767R0 §3 as seen by LWG in Varna
cplusplus/draft pull request #6274
Opened 2023-06-16 09:55 UTC by Quuxplusone

LWG reviewed this wording in Varna, approved it as suitably editorial, and we agreed that I should now submit it as a PR for @jwakely to look at.

This PR right now is structured as eight commits: two commits per container adaptor. For each adaptor, the first commit is literally the wording published in [P2767R0 §3](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2767r0.html#editorial-cons-alloc) and reviewed live in Varna. The second commit is amendments requested by LWG, to put the constructor overload sets in the traditional order (e.g. default constructor at the top). These second commits are editorial, and they're improvements over the status quo, and they were explicitly requested by LWG, but they _have not been published in a P-paper, and have not been reviewed yet._ Please see if they match your expectation!

Also, of course, I may have made typos in my transcription of even the first commits, so someone (@jwakely presumably) should still look through this and not just merge it blindly. Duh. :)

I expect this PR will be squash-merged with an updated commit message of some sort, and am happy to let whoever merges it figure that part out. Please let me know if you want me on my side to squash it and/or reword the commit message.

2023-07-13 16:51 UTC, Quuxplusone commented
@jwakely : Belated ping! I bet it's too late now to get this into the draft _before_ I submit P2767R1 based on top of it, but if I could have remembered to ping you last week, I should have...

2023-07-14 17:54 UTC, Quuxplusone commented
I just noticed that my original upload had missed adding the text
```
+\pnum
+The constructors in this subclause shall not participate in overload resolution
+unless \tcode{uses_allocator_v<key_container_type, Alloc>} is \tcode{true}
+and \tcode{uses_allocator_v<mapped_container_type, Alloc>} is \tcode{true}.
```
at the top of [flat.multimap.cons.alloc]. This is now fixed.

2023-08-08 14:05 UTC, Quuxplusone commented
Rebased to pick up the additions in 03da5baa (LWG3884). @jwakely ping!

2023-08-30 08:18 UTC, frederick-vs-ja commented
@jensmaurer Why is this PR considered able to close cplusplus/papers#1539? I think P2767 is largely non-editorial.

2023-08-30 08:26 UTC, Quuxplusone commented
> @jensmaurer Why is this PR considered able to close [cplusplus/papers#1539](https://github.com/cplusplus/papers/issues/1539)? I think P2767 is largely non-editorial.

@frederick-vs-ja You're correct, this PR absolutely would not "close" [cplusplus/papers#1539](https://github.com/cplusplus/papers/issues/1539), since it encompasses only one section (§3) of that whole paper. You're also correct that all the other sections are non-editorial (although some are at least non-design-level).

2023-08-30 08:32 UTC, Quuxplusone commented
Rebased to pick up aa8a5315136feb1af9084a2a914ba19cd8758a74 (typos in [flat.multiset]). @jwakely ping!

2023-08-30 17:52 UTC, jensmaurer commented
> Why is this PR considered able to close https://github.com/cplusplus/papers/issues/1539? I think P2767 is largely non-editorial.

Apologies, removed.

2023-10-12 22:28 UTC, Quuxplusone commented
@jwakely ping! (Remember we reviewed this wording in Varna?)

2024-05-19 18:57 UTC, Quuxplusone commented
@jwakely ping, please!

2024-06-10 11:03 UTC, jwakely requested changes

2024-06-10 11:03 UTC, jwakely commented on source/containers.tex
>                  const key_compare& comp, const Allocator& a);
```suggestion
                const key_compare& comp, const Alloc& a);
```

2024-06-10 11:05 UTC, jwakely commented on source/containers.tex
>                  const key_compare& comp, const Allocator& a);
This is the only actual error I found. This needs to be fixed. The missing param name should be fixed IMHO. The other two comments don't require action.

2024-06-10 20:42 UTC, jwakely commented on source/containers.tex
> +\rSec3[flat.set.cons.alloc]{Constructors with allocators}
But that's not true, there isn't only a single constructor, there are loads. We have a subclause for "constructors", then a sibling subclause for "some other constructors" ... but the "some other constructors" are also constructors, so why aren't they in the first one? Why do we have a subclause for constructors that's only got one of the constructors, not all the other constructors?

And we generally frown on having whole subclauses for single member functions. Three subclauses with one function each should be merged into one. In this case it's two subclauses, one with a single function and another with ... more than one. But it still seems unnecessary to add a subclause with its own heading and stable tag etc. for a single member function. We've been asking authors not to do that (e.g. in multiple places in the linalg paper).

But whatever, if this is going to change again then leave it.

2024-06-10 20:44 UTC, jwakely approved these changes

2024-06-10 21:06 UTC, merged