P2752R3 Static storage for braced initializers
cplusplus/draft pull request #6322
Opened 2023-06-18 08:55 UTC by jensmaurer

Fixes #6284
Fixes cplusplus/papers#1442

2023-06-18 10:12 UTC, cpplearner commented
Does it make sense to bump the `__cpp_initializer_lists` feature-test macro?

2023-06-18 11:15 UTC, JohelEGP requested changes
I'm using <https://isocpp.org/files/papers/D2752R3.html> to pre-review
(there are sufficient differences that I'll need to wait for the mailing to confirm).

2023-06-18 11:15 UTC, JohelEGP commented on source/compatibility.tex
> +bool b = ne({2,3}, {1,2,3}); // unspecified result; previously false
```suggestion
bool b = ne({2,3}, {1,2,3}); // unspecified result; previously \tcode{false}
```

2023-06-28 07:11 UTC, jensmaurer commented
> Does it make sense to bump the `__cpp_initializer_lists` feature-test macro?

This is a pure optimization enabler; I don't think it warrants a "feature" announcement.

2023-07-16 13:49 UTC, JohelEGP approved these changes
> (there are sufficient differences that I'll need to wait for the mailing to confirm).

It was actually alright.
The wording in the generated PDF looks as was proposed.
But it seems there was a change in the context
and the paper's PR wasn't rebased.

2023-07-16 21:18 UTC, tkoeppe commented
It seems that the paper is just presenting the status quo in a rather loose and lacunary fashion. The PR looks good. Thanks for checking!

2023-07-16 21:18 UTC, merged