P2741R3 User-generated static_assert messages
cplusplus/draft pull request #6325
Opened 2023-06-19 17:04 UTC by jensmaurer

Fixes #6285
Fixes cplusplus/papers#1434

2023-06-20 06:43 UTC, jensmaurer commented
This still needs conflict resolution with #6279. My idea is to simply rebase this branch onto the branch for the other motion.

@tkoeppe , would that work?

2023-06-20 09:36 UTC, tkoeppe commented
Sure, you can definitely base one PR on another branch. Is it clear how to reconcile the two motions?

2023-06-20 21:13 UTC, jensmaurer commented
> Is it clear how to reconcile the two motions?

Yes, there is very little actual overlap.

Rebased and conflicts fixed.

2023-06-26 15:56 UTC, JohelEGP requested changes

2023-06-26 15:56 UTC, JohelEGP commented on source/declarations.tex
> +implicitly convertible to the type ``pointer to \keyword{const} \keyword{char}''.
```suggestion
implicitly convertible to the type ``pointer to \tcode{\keyword{const} \keyword{char}}''.
```

2023-06-26 15:56 UTC, JohelEGP commented on source/declarations.tex
> +an unevaluated operand\iref{expr.context}.
```suggestion
an unevaluated operand\iref{term.unevaluated.operand}.
```

2023-06-26 15:56 UTC, JohelEGP commented on source/declarations.tex
> +an unevaluated operand\iref{expr.context}.
I think we need a check for this.
To avoid not using a label introduced for a term.

2023-06-26 15:56 UTC, JohelEGP commented on source/declarations.tex
> +the type ``pointer to \keyword{const} \keyword{char}'',
```suggestion
the type ``pointer to \tcode{\keyword{const} \keyword{char}}'',
```

2023-06-26 17:41 UTC, JohelEGP approved these changes

2023-07-16 21:36 UTC, merged