[Motions 2023 06 cwg 1] P2922R0 Core Language Working Group "ready" Issues
cplusplus/draft pull request #6328
Opened 2023-06-21 06:16 UTC by burblebee

Fixes #6276

2023-06-21 15:00 UTC, JohelEGP requested changes

2023-06-28 03:31 UTC, burblebee commented on source/declarations.tex
> +  using D1::i;                  // OK, equivalent to using \tcode{C::i}
thanks! fixed

2023-06-28 03:34 UTC, burblebee commented on source/lex.tex
> +\end{note}
Thanks! Resolving this for now.

2023-06-28 03:39 UTC, burblebee commented on source/lex.tex
> +Except for \grammarterm{integer-literal}{s} containing
Why? We typically encode Latex this way. Resolving - please reopen if you disagree.

2023-06-28 03:40 UTC, JohelEGP commented on source/lex.tex
> +Except for \grammarterm{integer-literal}{s} containing
The why is in the linked comment.

2023-06-28 03:49 UTC, burblebee commented on source/templates.tex
> +produces $\tcode{E}_1$, $\tcode{E}_2$, $\dotsc$, $\tcode{E}_N$.
Yes I did; reverted.

2023-06-28 13:42 UTC, JohelEGP approved these changes

2023-07-16 12:02 UTC, merged