[LWG motion 28] P2714R1 Bind front and back to NTTP callables
cplusplus/draft pull request #6339
Opened 2023-06-22 19:03 UTC by burblebee

Fixes #6314.

2023-06-26 14:52 UTC, JohelEGP requested changes

2023-06-26 14:52 UTC, JohelEGP commented on source/utilities.tex
> +does not have target object, and has the call pattern:
```suggestion
does not have a target object, and has the call pattern:
```

2023-06-28 06:40 UTC, burblebee commented on source/utilities.tex
> +does not have target object, and has the call pattern:
fixed, thanks!

2023-06-28 13:44 UTC, JohelEGP approved these changes

2023-07-21 22:37 UTC, merged