[LWG motion 23] P1759R6 Native handles and file streams
cplusplus/draft pull request #6347
Opened 2023-06-23 21:04 UTC by burblebee

Fixes #6309.

2023-06-25 14:32 UTC, JohelEGP requested changes

2023-06-25 14:32 UTC, JohelEGP commented on source/iostreams.tex
> +    using native_handle_type = @\textit{\impldef{type of \tcode{native_handle_type}}}@;;  // see \ref{file.native}
```suggestion
    using native_handle_type = @\textit{\impldef{type of \tcode{native_handle_type}}}@;  // see \ref{file.native}
```

2023-06-28 00:19 UTC, burblebee commented on source/iostreams.tex
> +    using native_handle_type = @\textit{\impldef{type of \tcode{native_handle_type}}}@;;  // see \ref{file.native}
done, thanks!

2023-06-28 00:20 UTC, JohelEGP approved these changes

2023-06-28 12:32 UTC, jwakely approved these changes

2023-07-21 21:00 UTC, merged