[meta.unary.prop.query, meta.trans.arr] Use `static_assert` instead of `assert` in example
cplusplus/draft pull request #6363
Opened 2023-06-29 14:57 UTC by hewillk

Not sure why runtime `assert` was used on [meta] in the first place.

2023-06-29 15:24 UTC, JohelEGP requested changes
Please, remove the redundant parentheses.

2023-06-29 15:26 UTC, jwakely commented
> Not sure why runtime `assert` was used on [meta] in the first place.

Because the example comes straight from TR1 which was based on C++03 and so there was no `static_assert` in the language.

2023-11-10 05:48 UTC, tkoeppe commented
Could you rerun the precommit checks?

2023-11-10 08:15 UTC, jwakely approved these changes

2023-11-10 08:59 UTC, merged