[flat.map][flat.multimap] Exposition-only formatting for `c`, `comp`, `compare`, and `key-equiv`
cplusplus/draft pull request #6404
Opened 2023-07-23 08:49 UTC by frederick-vs-ja

Also changes `key_equiv` to _`key-equiv`_.

I think it's OK to keep the member `comp` of `key_equiv` not marked `\exposid`, since the identifier `comp` is already reserved by `priority_queue::comp`. Implementations can use the name `comp` as-is or use another name.

`key_equiv` and `value_compare`'s exposition-only constructor are less than ideal to me. But I think they should be handled in an LWG issue because additional copy of comparator seems to be observable.

Follows up #5914. Fixes #5812.

2023-07-23 13:18 UTC, JohelEGP requested changes

2023-07-23 13:18 UTC, JohelEGP commented on source/containers.tex
> +\tcode{\exposid{compare}} with \tcode{comp}.
```suggestion
\exposid{compare} with \tcode{comp}.
```

2023-07-23 15:02 UTC, JohelEGP approved these changes

2023-11-10 09:16 UTC, tkoeppe commented
Thank you, this would be quite nice to land. @Dani-Hub, @CaseyCarter, would you perhaps be able to lend another pair of eyes?

2023-11-10 09:18 UTC, tkoeppe commented
@frederick-vs-ja Could you perhaps retrigger the precommit checks so we can get a downloadable PDF?

2023-11-10 10:15 UTC, Dani-Hub commented
> Thank you, this would be quite nice to land. @Dani-Hub, @CaseyCarter, would you perhaps be able to lend another pair of eyes?

I would happily do so, but I'm away during from an 30 minutes from now until Tuesday and I'm unable to do that right now.

2023-11-10 10:19 UTC, frederick-vs-ja commented
> @frederick-vs-ja Could you perhaps retrigger the precommit checks so we can get a downloadable PDF?

I've rebased and force-pushed, not sure whether this is sufficent...

2023-11-14 18:13 UTC, tkoeppe commented
@Dani-Hub Thanks! Yes, good point, we should fix those cases, too.

2024-04-16 16:50 UTC, frederick-vs-ja commented
@Dani-Hub @tkoeppe Sorry for noticing the comments so late. Now the changes are also applied to [flat.multiset.modifiers].

2024-04-16 17:15 UTC, Dani-Hub commented
> @Dani-Hub @tkoeppe Sorry for noticing the comments so late. Now the changes are also applied to [flat.multiset.modifiers].

Looks good to me - Thanks!

2024-09-28 01:37 UTC, frederick-vs-ja commented
Rebased & force-pushed to resolve some conflicts.

2024-11-10 10:58 UTC, jensmaurer approved these changes
Feels like an improvement.

@jwakely , what do you think?

2024-12-17 19:09 UTC, merged