[class.compare.default] Say subobjects of an object instead of a class
cplusplus/draft pull request #6425
Opened 2023-07-31 16:18 UTC by frederick-vs-ja

Fixes #5339.

2023-07-31 16:20 UTC, JohelEGP requested changes

2023-07-31 16:20 UTC, JohelEGP commented on source/classes.tex
> +followed by the direct member suobjects of \tcode{x},
```suggestion
followed by the direct member subobjects of \tcode{x},
```

2023-07-31 16:52 UTC, frederick-vs-ja commented on source/classes.tex
> +form a list of subobjects of for \tcode{x}.
Thanks! The intent is only using "for" ("for an object `x`" is used below).

2025-06-17 14:23 UTC, tkoeppe commented on source/classes.tex
> -followed by the non-static data members of \tcode{C},
Why are we losing "non-static" here? As far as I'm aware, static members don't create subobjects?

2025-06-18 01:48 UTC, frederick-vs-ja commented on source/classes.tex
> -followed by the non-static data members of \tcode{C},
This PR is switch to use "direct member subobjects". They're not equivalent as non-static member references are not member subobjects. But given [[class.compare.default]/2](https://eel.is/c++draft/class.compare.default#2) rejects non-static member references, I think it's more appropriate to say direct member subobjects.

2025-06-18 07:30 UTC, tkoeppe commented on source/classes.tex
> -followed by the non-static data members of \tcode{C},
Ah yes, I see, we're switching from members to subobjects below, too. Makes sense.

2026-05-04 13:42 UTC, jensmaurer reviewed
This looks good.

2026-05-04 13:42 UTC, jensmaurer approved these changes

2026-07-17 16:07 UTC, merged