[depr.static.constexpr] Cross-reference core clauses
cplusplus/draft pull request #6448
Opened 2023-08-08 21:21 UTC by AlisdairM

There is no back-link from the Annex D wording to the  feature that is deprecated.  The deprecation is mentioned in two places, so this PR links to both of them, and adds the corresponding missing link to the list item in [basic.def]

2023-08-08 21:23 UTC, JohelEGP requested changes

2023-08-08 21:23 UTC, JohelEGP commented on source/future.tex
> +initializer\iref{basic.def}\iref{class.static.data}.
```suggestion
initializer\iref{basic.def,class.static.data}.
```

2023-08-13 20:49 UTC, jensmaurer approved these changes

2023-08-13 21:13 UTC, JohelEGP commented
I'll pass on reviewing, since I don't know about the correctness of the PR.
My previous review was concerned about editorial changes.
That's why I sometimes don't re-review to approve.
Except for most Motions, where the Paper is the One Source of Truth.

2023-08-14 22:12 UTC, merged