P2662R3 Pack Indexing
cplusplus/draft pull request #6679
Opened 2023-11-12 21:25 UTC by jensmaurer

Fixes #6657

NOTE:

 - The paper renames class-or-decltpye to class-or-computed-type-specifier
in the grammar, but nowhere else.  There are references to class-or-decltype
in the narrative accompanying the grammar, those references are now pointing
to nowhere.

It is editorially-unclear whether the other mentions of class-or-decltype
should be bluntly replaced, or whether some of them shouldn't (maybe
because of special cases).

 - In expr.prim.id.qual, an "or" was struck, but nothing was added.
The only effect is to destroy the grammar of the sentence.
This can be editorially reverted, I think.

2023-11-12 22:35 UTC, JohelEGP requested changes
I used <https://isocpp.org/files/papers/P2662R3.pdf>.

2023-11-12 22:35 UTC, JohelEGP commented on source/expressions.tex
> +the $V^\tcode{th}$ element of the pack\iref{temp.variadic}.
Feel free to reject.
```suggestion
A \grammarterm{pack-index-expression} is a pack expansion\iref{temp.variadic}.

\pnum
\begin{note}
A \grammarterm{pack-index-expression} denotes
the $V^\tcode{th}$ element of the pack.
```

2023-11-12 22:35 UTC, JohelEGP commented on source/declarations.tex
> +the type of the $V^\tcode{th}$ element of the pack\iref{temp.variadic}.
Feel free to reject.
```suggestion
A \grammarterm{pack-index-specifier} is a pack expansion\iref{temp.variadic}.

\pnum
\begin{note}
The \grammarterm{pack-index-specifier} denotes
the type of the $V^\tcode{th}$ element of the pack.
```

2023-11-12 22:35 UTC, JohelEGP commented on source/templates.tex
> +The instantiation of P is the \grammarterm{typedef-name} $E_K$.
```suggestion
The instantiation of $P$ is the \grammarterm{typedef-name} $\tcode{E}_K$.
```

2023-11-12 22:35 UTC, JohelEGP commented on source/templates.tex
> +The instantiation of P is the \grammarterm{id-expression} $E_K$.
```suggestion
The instantiation of $P$ is the \grammarterm{id-expression} $\tcode{E}_K$.
```

2023-11-16 10:55 UTC, cor3ntin commented
> In expr.prim.id.qual, an "or" was struck, but nothing was added.
The only effect is to destroy the grammar of the sentence.
This can be editorially reverted, I think.

Yes, mistake on my part

> The paper renames class-or-decltpye to class-or-computed-type-specifier
in the grammar, but nowhere else. There are references to class-or-decltype
in the narrative accompanying the grammar, those references are now pointing
to nowhere.

I did review all use of `class-or-decltype` and they can all be replaced afaict.

2023-11-16 13:02 UTC, jensmaurer commented
> I did review all use of class-or-decltype and they can all be replaced afaict.

That may or may not be the case; I can't see such a replacement to be editorial (since we change what those places mean).

2023-11-17 12:15 UTC, JohelEGP approved these changes

2023-12-17 01:59 UTC, merged

2024-05-11 13:29 UTC, cor3ntin commented
@jensmaurer I just realized that the wording on top of page 18 does not seem to have been applied
Ie the grammar of `base-specifier was not modified.

2024-05-11 19:46 UTC, jensmaurer commented
The current state for _class-or-decltype_ is intentional; see c831ec0b8aac369aa61ce392783865ff04b84b19 .

However, in the production _class-or-decltype_, the option _decltype-specifier_ should have been changed to _computed-type-specifier_.