[Motions 2023 11 cwg 1] P3046R0 Core Language Working Group "ready" Issues
cplusplus/draft pull request #6684
Opened 2023-11-14 02:16 UTC by burblebee

Fixes #6655.

Notes:
* CWG1038 is fixed by CWG2725
* CWG1698 is fixed by CWG2747

2023-11-16 18:44 UTC, JohelEGP requested changes

2023-11-16 18:44 UTC, JohelEGP commented on source/expressions.tex
> +A pointer value of type ``pointer to \cv void''
![1700157938](https://github.com/cplusplus/draft/assets/21071787/4437fa14-5e83-4cd5-a83b-93ca7acbe667)
```suggestion
A pointer value of type ``pointer to \cv{}~\keyword{void}''
```

2023-11-16 18:44 UTC, JohelEGP commented on source/expressions.tex
> +is an unevaluated operand\iref{expr.context}.
```suggestion
is an unevaluated operand\iref{term.unevaluated.operand}.
```

2023-11-16 18:44 UTC, JohelEGP commented on source/expressions.tex
>  The operator yields an lvalue of type \tcode{T}
```suggestion
The operator yields an lvalue of type \tcode{T}.
```

2023-11-17 01:21 UTC, burblebee commented on source/expressions.tex
> +A pointer value of type ``pointer to \cv void''
thanks!

2023-11-17 01:31 UTC, burblebee commented on source/expressions.tex
> +is an unevaluated operand\iref{expr.context}.
Added in separate commit.

2023-11-17 01:37 UTC, JohelEGP approved these changes

2023-12-17 00:33 UTC, merged