[Motions 2024 03 cwg 1] P3196R0 (Core Language Working Group "ready" Issues)
cplusplus/draft pull request #6906
Opened 2024-03-27 09:13 UTC by burblebee

2024-04-04 19:46 UTC, jensmaurer requested changes

2024-04-15 00:09 UTC, tkoeppe commented on source/expressions.tex
> +a class member access expression.
Done!

2024-04-15 01:33 UTC, burblebee commented on source/expressions.tex
> +a class member access expression.
@tkoeppe thank you! been vacationing for a week (mostly out of cell/internet coverage), appreciate you filling in for me!

2024-04-15 06:58 UTC, jensmaurer approved these changes

2024-04-15 11:25 UTC, merged