[expr.new] Extend example for new-expressions with zero size arrays
cplusplus/draft pull request #7055
Opened 2024-06-10 21:24 UTC by Eisenwave

Someone has told me that they've been reading [[expr.new] p6](http://eel.is/c++draft/expr.new#6) wrong; namely in a way that implies `new int[0]` is ill-formed.

It's not immediately obvious that it is okay even though the wording says that something shall not be zero.

![image](https://github.com/cplusplus/draft/assets/22040976/fae39f54-4042-468c-9d78-fa93d75d5ac1)

2024-06-11 13:50 UTC, jensmaurer requested changes

2024-06-11 13:50 UTC, jensmaurer commented on source/expressions.tex
> +(because \tcode{0} is an \grammarterm{expression}), but
please use the same phrasing as the other sentence: "because 0 is the expression of a noptr-new-declarator"

2024-06-11 13:50 UTC, jensmaurer commented on source/expressions.tex
> +(because \tcode{0} is a \grammarterm{constant-expression}).
same here, and highlight that it's the value that's troublesome

2024-06-11 15:55 UTC, jensmaurer commented on source/expressions.tex
> +where a value of zero results in the allocation of an array with no elements), but
Can we get semantic linebreaks and move ", but" to the next line?

2024-08-05 16:46 UTC, tkoeppe commented
@jensmaurer could you have another look?

2024-08-05 20:01 UTC, jensmaurer approved these changes

2024-10-16 12:59 UTC, tkoeppe commented
This is nice, thanks!

2024-10-16 12:59 UTC, merged