[func.search.bm] Remove superfluous the
cplusplus/draft pull request #7160
Opened 2024-07-26 05:06 UTC by hewillk

2024-07-26 06:41 UTC, jensmaurer requested changes

2024-07-26 06:41 UTC, jensmaurer commented on source/utilities.tex
> +\oldconcept{Copy\-Constructible}, and \oldconcept{CopyAssignable} requirements.
Why did you reflow the list?  The three items in the list don't fit in one line, so should stay as three lines, to show the parallelism.  See also https://sembr.org/ .

Also, is the hyphenation hint for CopyConstructible still needed, now that there are fewer words in that particular line?

2024-07-26 07:51 UTC, jwakely commented
This change doesn't seem necessary, the existing text isn't wrong.

2024-07-26 09:08 UTC, jwakely commented
Yes. If that's the rationale for the change, it would have been helpful to say so.

2024-07-26 09:32 UTC, jwakely approved these changes
Looks OK to me if Jens is happy with the semantic breaks

2024-07-27 16:04 UTC, jensmaurer approved these changes

2024-07-27 16:05 UTC, merged