Merge 2024-11 LWG Motion 18 - P1928R15 std::simd — merge data-parallel types from the Parallelism TS 2
cplusplus/draft pull request #7437
Opened 2024-11-24 19:20 UTC by mattkretz

Fixes #7430
Fixes cplusplus/papers#670

This is still work-in-progress. Several overfull hboxes to be fixed. Also, I assume the local use of `\newcommand` macros is not something I should keep, yes?

2024-11-24 19:41 UTC, jensmaurer requested changes
no complete, but a start

2024-11-24 19:41 UTC, jensmaurer commented on source/numerics.tex
> +The set of \defn{vectorizable types} comprises all standard integer types,
Please use \defnadjx so that we get index entries for both "vectorizable type" and "type, vectorizable".

2024-11-24 19:41 UTC, jensmaurer commented on source/numerics.tex
> +The term \defn{data-parallel type} refers to all enabled specializations of
\defnadj

2024-11-24 19:41 UTC, jensmaurer commented on source/numerics.tex
> +the \tcode{basic_simd} and \tcode{basic_simd_mask} class templates. A \defn{data-parallel object} is
\defnadj

2024-11-24 19:41 UTC, jensmaurer commented on source/numerics.tex
> +an object of \term{data-parallel type}.
Defined phrases are italicized once when defined, and not when referred to. Please remove \term here.

2024-11-24 19:41 UTC, jensmaurer commented on source/numerics.tex
> +An \defn{element-wise operation} applies a specified operation to the elements of one or more
\defnadj

2024-11-24 19:41 UTC, jensmaurer commented on source/numerics.tex
> +\defn{selected indices} signify the integers $i$ in the range
\defnadj

2024-11-24 19:41 UTC, jensmaurer commented on source/numerics.tex
> +Given a data-parallel object \tcode{data}, the \defn{selected elements} signify the elements
\defnadj

2024-11-24 19:41 UTC, jensmaurer commented on source/numerics.tex
> +\rSec2[simd.expos]{Exposition only types, variables, and concepts}
```suggestion
\rSec2[simd.expos]{Exposition-only types, variables, and concepts}
```

2024-11-25 11:43 UTC, closed without merging

2024-11-25 11:44 UTC, mattkretz commented
Ah whatever GitHub. I renamed the branch to match https://github.com/cplusplus/draft/wiki/Commit-message-format. I'll open a new PR.