P3379R0 Constrain std::expected equality operators
cplusplus/draft pull request #7449
Opened 2024-11-27 19:02 UTC by jensmaurer

Fixes #7416 
Also fixes cplusplus/papers#2036

2024-11-27 19:09 UTC, jwakely requested changes
There's a missing edit to [version.syn]:

> Update the value of the __cpp_lib_constrained_equality feature test macro in [version.syn].

2024-11-27 20:12 UTC, jensmaurer commented
@jwakely , fixed the missing version bump

I think we've decided before that feature-test macros are sort-of editorial, so I've added the `<expected>` amendment with a separate commit.

2024-11-27 20:21 UTC, jwakely approved these changes

2024-12-16 18:49 UTC, tkoeppe approved these changes

2024-12-16 20:19 UTC, merged